import Pnp4.AlgorithmsToLowerBounds.AC0pAsymptoticBridge
import Pnp4.AlgorithmsToLowerBounds.AC0pSuperPolynomialBridge
import Pnp4.AlgorithmsToLowerBounds.MCSP_AC0p_Final
import Pnp4.AlgorithmsToLowerBounds.MCSP_AC0p_Quantitative
import Pnp4.AlgorithmsToLowerBounds.AC0pCoinAsymptotic
import Pnp4.AlgorithmsToLowerBounds.CoinMaskingTranslation
import Pnp4.AlgorithmsToLowerBounds.MCSPCoinReductionContract
import Pnp4.AlgorithmsToLowerBounds.LocalPRGHardnessSpec
import Pnp4.AlgorithmsToLowerBounds.FormulaCircuitPublishedLowerBound
import Pnp4.AlgorithmsToLowerBounds.FormulaCircuitTargetModel
import Pnp4.AlgorithmsToLowerBounds.MCSP_Formula_Final
import Pnp4.AlgorithmsToLowerBounds.MCSP_Formula_Theorem2Quantitative
import Pnp4.AlgorithmsToLowerBounds.FormulaCircuitAsymptotic
import Pnp4.AlgorithmsToLowerBounds.BridgeToPpolyDAG
import Pnp4.Frontier.PvsNPBridgeRequirements
import Pnp4.Frontier.CompressionMagnification
import Pnp4.Frontier.SearchMCSPMagnification
import Pnp4.Frontier.SearchMCSPConcreteTargets
import Pnp4.Frontier.ContractExpansion.C_DAG_Adapter
import Pnp4.Frontier.ContractExpansion.QueryComposition
import Pnp4.Frontier.ContractExpansion.QueryBuilder
import Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguage
import Pnp4.Frontier.ContractExpansion.PrefixQueryBuilder
import Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguageRuntime
import Pnp4.Frontier.ContractExpansion.PrefixParserConvention
import Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixSerializer
import Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixQueryCircuits
import Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixStateQueryCircuits
import Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyBundleStep
import Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyBundleFold
import Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyOutputCircuits
import Pnp4.Frontier.ContractExpansion.PrefixExtendableSplit
import Pnp4.Frontier.ContractExpansion.TreeMCSPTrueExtensionQuery
import Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyExtendable
import Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyTrueOutputCircuits
import Pnp4.Frontier.ContractExpansion.TreeMCSPDeciderCorrect
import Pnp4.Frontier.ContractExpansion.TreeMCSPGreedySolves
import Pnp4.Frontier.ContractExpansion.TreeMCSPBoundedSolver
import Pnp4.Frontier.ContractExpansion.BoundedSolverFromPpoly
import Pnp4.Frontier.ContractExpansion.NoSolverContrapositive
import Pnp4.Frontier.ContractExpansion.ExtractedScheduleGrowth
import Pnp4.Frontier.ContractExpansion.ConditionalVerifiedSource
import Pnp4.Frontier.ContractExpansion.WitnessGrowthReduction
import Pnp4.Frontier.ContractExpansion.PrefixExtensionNPWitness
import Pnp4.Frontier.ContractExpansion.ExplicitConditionalSource
import Pnp4.Frontier.ContractExpansion.ConcreteCodecGap
import Pnp4.Frontier.ContractExpansion.CircuitTreeBridge
import Pnp4.Frontier.ContractExpansion.CircuitEncodingLength
import Pnp4.Frontier.ContractExpansion.CircuitDecodeDepthFree
import Pnp4.Frontier.ContractExpansion.ConcreteTreeCodec
import Pnp4.Frontier.ContractExpansion.ConcreteTreeCodecSource
import Pnp4.Frontier.ContractExpansion.ThresholdGrowth
import Pnp4.Frontier.ContractExpansion.ConsolidatedTreeSeparation
import Pnp4.Frontier.ContractExpansion.TreeMCSPZeroPrefixBuilder
import Pnp4.Frontier.ContractExpansion.NaiveGreedySizeSpike
import Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixSemanticVerifier
import Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixVerifierLayout
import Pnp4.Frontier.ContractExpansion.BoundedLoopProgram
import Pnp4.Frontier.ContractExpansion.PhasedProgramAccepts
import Pnp4.Frontier.ContractExpansion.TreeMCSPTagCheckProgram
import Pnp4.Frontier.ContractExpansion.TreeMCSPTagCheckUnit
import Pnp4.Frontier.ContractExpansion.TreeMCSPGammaScanProgram
import Pnp4.Frontier.ContractExpansion.TreeMCSPScanLeftProgram
import Pnp4.Frontier.ContractExpansion.TreeMCSPScanLeftOneProgram
import Pnp4.Frontier.ContractExpansion.TreeMCSPScanRightOneProgram
import Pnp4.Frontier.ContractExpansion.TreeMCSPGateRecordLayout
import Pnp4.Frontier.ContractExpansion.TreeMCSPUnaryFieldReader
import Pnp4.Frontier.ContractExpansion.TreeMCSPGateTagDispatch
import Pnp4.Frontier.ContractExpansion.TreeMCSPGateRecordDecoder
import Pnp4.Frontier.ContractExpansion.TreeMCSPGateStreamLayout
import Pnp4.Frontier.ContractExpansion.TreeMCSPLoopUntilSink
import Pnp4.Frontier.ContractExpansion.TreeMCSPCountdownLeft
import Pnp4.Frontier.ContractExpansion.TreeMCSPGammaFillProgram
import Pnp4.Frontier.ContractExpansion.TreeMCSPGammaFillComposition
import Pnp4.Frontier.ContractExpansion.TreeMCSPRepeatBody
import Pnp4.Frontier.ContractExpansion.TreeMCSPBidirHeadBounds
import Pnp4.Frontier.ContractExpansion.TreeMCSPSelfLoopCounter
import Pnp4.Frontier.ContractExpansion.TreeMCSPCounterComposition
import Pnp4.Frontier.ContractExpansion.TreeMCSPScanComposition
import Pnp4.Frontier.ContractExpansion.TreeMCSPTagCheckComposition
import Pnp4.Frontier.ContractExpansion.TreeMCSPLeadingPhasesChain
import Pnp4.Frontier.ContractExpansion.TreeMCSPSkeletonComposition

namespace Pnp4
namespace Tests

#print axioms AlgorithmsToLowerBounds.maskBit_true
#print axioms AlgorithmsToLowerBounds.maskBit_false
#print axioms AlgorithmsToLowerBounds.maskVec_apply
#print axioms AlgorithmsToLowerBounds.expectationProductBias_sub
#print axioms AlgorithmsToLowerBounds.expectationProductBias_le_of_pointwise_le
#print axioms AlgorithmsToLowerBounds.exists_max_bitVec_rat
#print axioms AlgorithmsToLowerBounds.maskedAcceptanceAverage_eq_acceptanceProbability_mul
#print axioms AlgorithmsToLowerBounds.MaskingBiasParams.keepBias_nonneg
#print axioms AlgorithmsToLowerBounds.MaskingBiasParams.keepBias_le_one
#print axioms AlgorithmsToLowerBounds.MaskingBiasParams.keepBias_mul_highTargetBias
#print axioms AlgorithmsToLowerBounds.MaskingBiasParams.keepBias_mul_lowTargetBias
#print axioms AlgorithmsToLowerBounds.maskedAcceptanceAdvantage_eq_expectation_fixed
#print axioms AlgorithmsToLowerBounds.MaskAveragingContract.of_valid_keepBias
#print axioms AlgorithmsToLowerBounds.MaskAveragingContract.of_maskingBiasParams
#print axioms AlgorithmsToLowerBounds.MaskingPushforwardFacts.of_maskingBiasParams
#print axioms AlgorithmsToLowerBounds.CoinMaskingTranslationFacts.of_maskingBiasParams
#print axioms AlgorithmsToLowerBounds.MaskingPushforwardFacts.masked_advantage_eq_source
#print axioms AlgorithmsToLowerBounds.CoinMaskingTranslationFacts.exists_mask_with_source_advantage
#print axioms AlgorithmsToLowerBounds.bestMaskForCircuit
#print axioms AlgorithmsToLowerBounds.bestMaskForCircuit_max
#print axioms AlgorithmsToLowerBounds.source_advantage_le_bestMask_fixed_advantage
#print axioms AlgorithmsToLowerBounds.coinTranslationPreservesClass_of_maskingSetup
#print axioms AlgorithmsToLowerBounds.AC0pFamilyModelWithMasking.closed
#print axioms AlgorithmsToLowerBounds.coinTranslationPreservesClass_of_maskingSetup_AC0p
#print axioms AlgorithmsToLowerBounds.false_of_AC0p_circuit_family_computes_adjacentBias_MCSP_hardDecision_of_maskingSetup
#print axioms AlgorithmsToLowerBounds.maskingParams_of_adjacentBiasToHalfVsFair
#print axioms AlgorithmsToLowerBounds.CoinMaskingTranslationSetup.of_adjacentBiasToHalfVsFair
#print axioms AlgorithmsToLowerBounds.false_of_AC0p_circuit_family_computes_adjacentBias_MCSP_hardDecision_of_adjacentMaskingSetup
#print axioms AlgorithmsToLowerBounds.quasiPolyLower_superPolynomialGrowth
#print axioms AlgorithmsToLowerBounds.not_hasPolynomialSizeFamily_of_superPolynomial_lowerBound
#print axioms AlgorithmsToLowerBounds.not_hasPolynomialSizeFamily_of_quasiPolynomial_lowerBound
#print axioms AlgorithmsToLowerBounds.EventuallySizeLowerBound.weaken
#print axioms AlgorithmsToLowerBounds.not_hasPolynomialSizeFamily_of_eventual_superPolynomial_lowerBound
#print axioms AlgorithmsToLowerBounds.not_hasPolynomialSizeFamily_of_eventual_quasiPolynomial_lowerBound
#print axioms AlgorithmsToLowerBounds.not_depth_d_AC0p_of_quasiPoly_lowerBound
#print axioms AlgorithmsToLowerBounds.not_in_AC0p_of_depthwise_quasiPoly_lowerBound
#print axioms AlgorithmsToLowerBounds.not_in_AC0p_from_quasiPolynomial_contract
#print axioms AlgorithmsToLowerBounds.not_depth_d_AC0p_of_eventual_quasiPoly_lowerBound
#print axioms AlgorithmsToLowerBounds.not_in_AC0p_of_depthwise_eventual_quasiPoly_lowerBound
#print axioms AlgorithmsToLowerBounds.not_in_AC0p_from_asymptotic_quasiPolynomial_contract
#print axioms AlgorithmsToLowerBounds.smallCircuit_contradiction_of_localPRGTransfer
#print axioms AlgorithmsToLowerBounds.sizeLowerBound_exactTreeMCSPThresholdLanguage_of_localPRGTransfer
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_publishedOneSidedLocalPRGRoute
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_publishedLocalPRGRoute
#print axioms AlgorithmsToLowerBounds.formulaCircuit_MCSP_lower_bound_from_publishedLocalPRGRoute
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_formulaCircuitPublishedLocalPRGRoute
#print axioms AlgorithmsToLowerBounds.formulaCircuit_MCSP_lower_bound_from_publishedLowerBoundContract
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_publishedLowerBoundContract
#print axioms AlgorithmsToLowerBounds.formulaCircuit_MCSP_lower_bound_from_CKLMFormulaCircuitRoute
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_CKLMFormulaCircuitRoute
#print axioms AlgorithmsToLowerBounds.formulaCircuit_MCSP_lower_bound_from_CKLMFormulaCircuitTheorem2Contract
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_CKLMFormulaCircuitTheorem2Contract
#print axioms AlgorithmsToLowerBounds.formulaCircuit_MCSP_lower_bound_from_CKLMFormulaCircuitTheorem2QuantitativeContract
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_CKLMFormulaCircuitTheorem2QuantitativeContract
#print axioms AlgorithmsToLowerBounds.formulaCircuit_MCSP_lower_bound_from_CKLMFormulaCircuitLocalPRGSource
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_CKLMFormulaCircuitLocalPRGSource
#print axioms AlgorithmsToLowerBounds.no_PpolyFormula_of_formulaCircuitPublishedLowerBoundContract_and_growth
#print axioms AlgorithmsToLowerBounds.no_PpolyFormula_of_formulaCircuitPublishedLocalPRGRoute_and_growth
#print axioms AlgorithmsToLowerBounds.no_PpolyFormula_of_CKLM_formulaOrBranchingProgramRoute_and_growth
#print axioms AlgorithmsToLowerBounds.no_PpolyFormula_of_CKLMFormulaCircuitLocalPRGSource_and_growth
#print axioms AlgorithmsToLowerBounds.not_beatsEveryPpolyBoundAtSomeTableLength_cklmEnvelope
#print axioms AlgorithmsToLowerBounds.not_beatsEveryPpolyBoundFrequentlyAtSomeTableLength_cklmEnvelope
#print axioms AlgorithmsToLowerBounds.no_uniform_cklmEnvelopeFrequentEscape
#print axioms AlgorithmsToLowerBounds.productBiasWeight_total
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_true
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_not
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_not_le_of_one_sub_le
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_mono
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_mono_lowBias
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_mono_highBias
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_fair_eq_bitVecAcceptanceProbability
#print axioms AlgorithmsToLowerBounds.bitVecAcceptanceProbability_not
#print axioms AlgorithmsToLowerBounds.one_sub_upper_le_acceptanceProbability_fair_not
#print axioms AlgorithmsToLowerBounds.solvesCoinProblem_of_acceptanceProbability_bounds
#print axioms AlgorithmsToLowerBounds.BoundedClassSolvesCoinProblem.mono_size
#print axioms AlgorithmsToLowerBounds.MCSPThresholdOracle.accepts_of_treeMCSPPredicate
#print axioms AlgorithmsToLowerBounds.MCSPThresholdOracle.rejects_of_not_treeMCSPPredicate
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinReductionContract.of_distributionFacts
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinReductionContract.of_treeMCSPPredicateMassFacts
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinRejectionProfile.hard_solvesCoin
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinRejectionContract.of_notTreeMCSPPredicateMassFacts
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinRejectionContract.of_treeMCSPPredicateBiasedLower_and_fairCounting
#print axioms AlgorithmsToLowerBounds.CoinDistinguisherFamily.solves_instance
#print axioms AlgorithmsToLowerBounds.CircuitCoinDistinguisherFamily.solves
#print axioms AlgorithmsToLowerBounds.CircuitCoinDistinguisherFamily.boundedSolves
#print axioms AlgorithmsToLowerBounds.AdjacentBiasMCSPThresholdSeparationFacts.toSolvesCoin
#print axioms AlgorithmsToLowerBounds.CoinDistinguisherFamily.of_adjacentBiasMCSP
#print axioms AlgorithmsToLowerBounds.CircuitCoinDistinguisherFamily.of_adjacentBiasMCSP_circuit
#print axioms AlgorithmsToLowerBounds.CoinDistinguisherToHalfVsFairTranslationContract.solvesCoin
#print axioms AlgorithmsToLowerBounds.halfVsFairCoinDistinguisherFamily
#print axioms AlgorithmsToLowerBounds.CircuitCoinDistinguisherFamily.translate_to_halfVsFair
#print axioms AlgorithmsToLowerBounds.BoundedClassSolvesCoinProblem_of_translated_realization
#print axioms AlgorithmsToLowerBounds.false_of_translated_realization_and_AC0pCoinLowerBound
#print axioms AlgorithmsToLowerBounds.false_of_adjacentBias_realization_translation_and_AC0pCoinLowerBound
#print axioms AlgorithmsToLowerBounds.false_of_AC0p_circuit_family_computes_adjacentBias_MCSP_hardDecision
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinRejectionContract.of_adjacentBiasSeparation_and_translation
#print axioms AlgorithmsToLowerBounds.treeMCSPCountRatio_le_one_sub_self_fairLower
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinRejectionContract.of_biasedLowComplexityMassFacts
#print axioms AlgorithmsToLowerBounds.HalfVsFairMCSPCoinRejectionContract.hard_solvesCoin
#print axioms AlgorithmsToLowerBounds.treeMCSPPredicateDecision_spec
#print axioms AlgorithmsToLowerBounds.notTreeMCSPPredicateDecision_spec
#print axioms AlgorithmsToLowerBounds.exactTreeMCSPThresholdHardDecision_spec
#print axioms AlgorithmsToLowerBounds.uniformTruthTableAcceptanceProbability_treeMCSPPredicateDecision_le_countRatio
#print axioms AlgorithmsToLowerBounds.fairAcceptanceProbability_treeMCSPPredicateDecision_le_countRatio
#print axioms AlgorithmsToLowerBounds.one_sub_countRatio_le_fairAcceptanceProbability_notTreeMCSPPredicateDecision
#print axioms AlgorithmsToLowerBounds.halfVsFair_highBias_treeMCSPPredicateDecision_le_countRatio
#print axioms AlgorithmsToLowerBounds.one_sub_countRatio_le_halfVsFair_highBias_exactTreeMCSPThresholdHardDecision
#print axioms AlgorithmsToLowerBounds.halfVsFair_lowBias_exactTreeMCSPThresholdHardDecision_le_of_treeMCSPPredicate_mass_lower
#print axioms AlgorithmsToLowerBounds.exactTreeMCSPThresholdDecision_accepts_of_treeMCSPPredicate
#print axioms AlgorithmsToLowerBounds.exactTreeMCSPThresholdDecision_rejects_of_not_treeMCSPPredicate
#print axioms AlgorithmsToLowerBounds.exactTreeMCSPThresholdHardDecision_accepts_of_not_treeMCSPPredicate
#print axioms AlgorithmsToLowerBounds.exactTreeMCSPThresholdHardDecision_rejects_of_treeMCSPPredicate
#print axioms AlgorithmsToLowerBounds.acceptanceProbability_exactTreeMCSPThresholdDecision_le_treeMCSPPredicateDecision
#print axioms AlgorithmsToLowerBounds.treeMCSPPredicateDecision_le_acceptanceProbability_exactTreeMCSPThresholdDecision
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_AC0pCoinLowerBound
#print axioms AlgorithmsToLowerBounds.sizeLowerBound_exactTreeMCSPThresholdLanguage_of_AC0pCoinLowerBound
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_AC0pCoinLowerBound
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_AC0pCoinLowerBound_and_reduction
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_AC0pCoinLowerBound_and_reduction
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_AC0pCoinQuantitativeContract
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_AC0pCoinQuantitativeContract
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_AC0pCoinQuantitativeContract_and_reduction
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_AC0pCoinQuantitativeContract_and_reduction
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_AC0pCoinPublishedExpLowerBoundContract
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_AC0pCoinPublishedExpLowerBoundContract
#print axioms AlgorithmsToLowerBounds.noSmallImplementedThresholdOracle_of_AC0pCoinPublishedExpLowerBoundContract_and_reduction
#print axioms AlgorithmsToLowerBounds.MCSP_lower_bound_from_AC0pCoinPublishedExpLowerBoundContract_and_reduction
#print axioms AlgorithmsToLowerBounds.halfVsFairMCSPCoinAsymptoticLanguage_eq_slice_at_tableLen
#print axioms AlgorithmsToLowerBounds.ac0pCoinLowerEnvelope_beatsEveryPolynomial_at_arbitrarilyLarge_tableLengths
#print axioms AlgorithmsToLowerBounds.not_hasPolynomialSizeFamily_halfVsFairMCSPCoinAsymptoticLanguage
#print axioms AlgorithmsToLowerBounds.not_in_AC0p_halfVsFairMCSPCoinAsymptoticLanguage_from_published_contract_and_growth
#print axioms AlgorithmsToLowerBounds.not_in_AC0p_halfVsFairMCSPCoinAsymptoticLanguage_from_published_contract
#print axioms AlgorithmsToLowerBounds.P_ne_NP_of_verified_source
#print axioms Frontier.AC0pRestrictedLowerBoundSource.restrictedConclusion
#print axioms Frontier.P_ne_NP_of_pnp4_bridge_requirement
#print axioms Frontier.P_ne_NP_of_restricted_source_and_dag_bridge
#print axioms Frontier.P_ne_NP_of_NP_not_subset_Ppoly
#print axioms Frontier.SearchMCSPWeakLowerBound.verifiedSource
#print axioms Frontier.NP_not_subset_Ppoly_of_searchMCSPWeakLowerBound
#print axioms Frontier.P_ne_NP_of_searchMCSPWeakLowerBound
#print axioms Frontier.P_ne_NP_of_mainlineProgress
#print axioms Frontier.PvsNPMainlineProgress.of_searchMCSPWeakLowerBound
#print axioms Frontier.SearchMCSPWeakLowerBound.of_weakCircuitLowerBound
#print axioms Frontier.SearchMCSPWeakCircuitLowerBound.verifiedSource
#print axioms Frontier.NP_not_subset_Ppoly_of_weakCircuitLowerBound
#print axioms Frontier.P_ne_NP_of_weakCircuitLowerBound
#print axioms Frontier.PvsNPMainlineProgress.of_weakCircuitLowerBound
#print axioms Frontier.treeMCSPSearchProblem
#print axioms Frontier.treeMCSPSearchWeakLowerBoundTarget
#print axioms Frontier.TreeCircuitWitnessCodec.sound
#print axioms Frontier.TreeCircuitWitnessCodec.complete
#print axioms Frontier.TreeMCSPSearchWitnessEncoding.ofCodec
#print axioms Frontier.TreeMCSPSearchMagnificationSource.verifiedSource
#print axioms Frontier.NP_not_subset_Ppoly_of_treeMCSPSearchMagnificationSource
#print axioms Frontier.P_ne_NP_of_treeMCSPSearchMagnificationSource
#print axioms Frontier.PvsNPMainlineProgress.of_treeMCSPSearchMagnificationSource

end Tests
end Pnp4

#print axioms Pnp4.Frontier.ContractExpansion.InPpolyDAG_to_C_DAG_family
#print axioms Pnp4.Frontier.ContractExpansion.C_DAG_family_to_InPpolyDAG
#print axioms Pnp4.Frontier.ContractExpansion.PpolyDAG_decider_as_C_DAG_decider

#print axioms Pnp4.Frontier.ContractExpansion.eval_composeDeciderWithQuery
#print axioms Pnp4.Frontier.ContractExpansion.size_composeDeciderWithQuery_le

#print axioms Pnp4.Frontier.ContractExpansion.QueryCircuitBuilder.eval_compose
#print axioms Pnp4.Frontier.ContractExpansion.QueryCircuitBuilder.size_compose_le
#print axioms Pnp4.Frontier.ContractExpansion.QueryCircuitBuilder.size_compose_le_bound

#print axioms Pnp4.Frontier.ContractExpansion.PrefixQueryBuilder.eval_compose
#print axioms Pnp4.Frontier.ContractExpansion.PrefixQueryBuilder.size_compose_le
#print axioms Pnp4.Frontier.ContractExpansion.PrefixQueryBuilder.queryValue_parses

#print axioms Pnp4.Frontier.ContractExpansion.parse_zeroPrefixQueryValue
#print axioms Pnp4.Frontier.ContractExpansion.zeroPrefixQueryValue_parses

#print axioms Pnp4.Frontier.ContractExpansion.eval_zeroPrefixQueryBitCircuit
#print axioms Pnp4.Frontier.ContractExpansion.size_zeroPrefixQueryBitCircuit_le

#print axioms Pnp4.Frontier.ContractExpansion.parse_prefixStateQueryValue
#print axioms Pnp4.Frontier.ContractExpansion.prefixStateQueryValue_parses
#print axioms Pnp4.Frontier.ContractExpansion.eval_prefixStateQueryBitCircuit
#print axioms Pnp4.Frontier.ContractExpansion.size_prefixStateQueryBitCircuit_le

#print axioms Pnp4.Frontier.ContractExpansion.gates_greedyBundleStep
#print axioms Pnp4.Frontier.ContractExpansion.size_greedyStepHead_le
#print axioms Pnp4.Frontier.ContractExpansion.evalOutput_greedyBundleStep_old
#print axioms Pnp4.Frontier.ContractExpansion.evalOutput_greedyBundleStep_new

#print axioms Pnp4.Frontier.ContractExpansion.gates_greedyBundleUpTo_succ
#print axioms Pnp4.Frontier.ContractExpansion.gates_greedyBundleUpTo_le
#print axioms Pnp4.Frontier.ContractExpansion.evalOutput_greedyBundleUpTo_old
#print axioms Pnp4.Frontier.ContractExpansion.evalOutput_greedyBundleUpTo_new

#print axioms Pnp4.Frontier.ContractExpansion.eval_greedyOutputCircuit
#print axioms Pnp4.Frontier.ContractExpansion.size_greedyOutputCircuit_le

#print axioms Pnp4.Frontier.ContractExpansion.prefixExtendableInput_iff_witnessPrefixExtendable
#print axioms Pnp4.Frontier.ContractExpansion.witnessPrefixExtendable_split
#print axioms Pnp4.Frontier.ContractExpansion.witnessPrefixExtendable_snoc_false_of_not_true
#print axioms Pnp4.Frontier.ContractExpansion.witnessPrefixExtendable_snoc_true_of_not_false

#print axioms Pnp4.Frontier.ContractExpansion.eval_prefixTrueExtensionQueryBitCircuit
#print axioms Pnp4.Frontier.ContractExpansion.size_prefixTrueExtensionQueryBitCircuit_le
#print axioms Pnp4.Frontier.ContractExpansion.size_greedyTrueStepHead_le
#print axioms Pnp4.Frontier.ContractExpansion.greedyPrefix_succ
#print axioms Pnp4.Frontier.ContractExpansion.greedyPrefix_extendable

#print axioms Pnp4.Frontier.ContractExpansion.gates_greedyTrueBundleUpTo_le
#print axioms Pnp4.Frontier.ContractExpansion.eval_greedyTrueOutputCircuit
#print axioms Pnp4.Frontier.ContractExpansion.size_greedyTrueOutputCircuit_le

#print axioms Pnp4.Frontier.ContractExpansion.correctNextBitDecider_of_decidesLanguage

#print axioms Pnp4.Frontier.ContractExpansion.greedyPrefix_solves
#print axioms Pnp4.Frontier.ContractExpansion.searchSolverOutput_greedyTrueOutputCircuit
#print axioms Pnp4.Frontier.ContractExpansion.greedyTrueOutputCircuit_solves

#print axioms Pnp4.Frontier.ContractExpansion.boundedSearchSolver_of_deciderFamily
#print axioms Pnp4.Frontier.ContractExpansion.boundedSearchSolver_of_PpolyDAG_prefixExtension
#print axioms Pnp4.Frontier.ContractExpansion.not_PpolyDAG_prefixExtension_of_noExtractedScheduleSolver

#print axioms Pnp4.Frontier.ContractExpansion.nonempty_boundedSearchSolver_mono_sizeBound
#print axioms Pnp4.Frontier.ContractExpansion.noExtractedScheduleSolver_of_noPolynomial
#print axioms Pnp4.Frontier.ContractExpansion.not_PpolyDAG_prefixExtension_of_noPolynomialBoundedSearchSolver

#print axioms Pnp4.Frontier.ContractExpansion.verifiedSource_of_noPolynomialBoundedSearchSolver
#print axioms Pnp4.Frontier.ContractExpansion.NP_not_subset_PpolyDAG_of_noPolynomialBoundedSearchSolver

#print axioms Pnp4.Frontier.ContractExpansion.bitLength_le_self
#print axioms Pnp4.Frontier.ContractExpansion.polyBoundedInTable_treeMCSPPrefixM_of_witnessPoly
#print axioms Pnp4.Frontier.ContractExpansion.treeMCSPExtractionGrowthAssumptions_of_witnessPoly
#print axioms Pnp4.Frontier.ContractExpansion.PolynomialWitnessCodec.toGrowthAssumptions

#print axioms Pnp4.Frontier.ContractExpansion.prefixExtensionLanguage_in_NP_of_witness

#print axioms Pnp4.Frontier.ContractExpansion.verifiedSource_of_explicit_interfaces
#print axioms Pnp4.Frontier.ContractExpansion.NP_not_subset_PpolyDAG_of_explicit_interfaces

#print axioms Pnp4.Frontier.ContractExpansion.ofFn_listToFixedBitVec
#print axioms Pnp4.Frontier.ContractExpansion.SelfDelimitingCircuitCode.toCodec

#print axioms Pnp4.Frontier.ContractExpansion.fromTree_toTree
#print axioms Pnp4.Frontier.ContractExpansion.toTree_fromTree
#print axioms Pnp4.Frontier.ContractExpansion.size_toTree
#print axioms Pnp4.Frontier.ContractExpansion.decodeCircuit_encodeCircuit

#print axioms Pnp4.Frontier.ContractExpansion.length_encodeCircuitTree_le
#print axioms Pnp4.Frontier.ContractExpansion.length_encodeCircuit_le

#print axioms Pnp4.Frontier.ContractExpansion.length_encodeCircuit_ge
#print axioms Pnp4.Frontier.ContractExpansion.decodeCircuitFull_encodeCircuit

#print axioms Pnp4.Frontier.ContractExpansion.treeCircuitWitnessCodec
#print axioms Pnp4.Frontier.ContractExpansion.polyBoundedInTable_treeWitnessBits_of_thresholdPoly
#print axioms Pnp4.Frontier.ContractExpansion.treePolynomialWitnessCodec

#print axioms Pnp4.Frontier.ContractExpansion.verifiedSource_of_treeCodec_noPolynomialBoundedSearchSolver
#print axioms Pnp4.Frontier.ContractExpansion.NP_not_subset_PpolyDAG_of_treeCodec_interfaces

#print axioms Pnp4.Frontier.ContractExpansion.polyBoundedInTable_thresholdLinear
#print axioms Pnp4.Frontier.ContractExpansion.polyBoundedInTable_thresholdQuadratic
#print axioms Pnp4.Frontier.ContractExpansion.polyBoundedInTable_thresholdPoly

#print axioms Pnp4.Frontier.ContractExpansion.verifiedSource_treePoly
#print axioms Pnp4.Frontier.ContractExpansion.NP_not_subset_PpolyDAG_treePoly

#print axioms Pnp4.Frontier.ContractExpansion.zeroPrefixQueryCircuitBuilder
#print axioms Pnp4.Frontier.ContractExpansion.treeMCSPZeroPrefixQueryBuilder
#print axioms Pnp4.Frontier.ContractExpansion.treeMCSPZeroPrefixQueryBuilder_queryValue

#print axioms Pnp4.Frontier.ContractExpansion.geometric_lower_bound
#print axioms Pnp4.Frontier.ContractExpansion.composeDeciderWithQuery_eq_substInputs
#print axioms Pnp4.Frontier.ContractExpansion.naiveGreedyModel_size_ge
#print axioms Pnp4.Frontier.ContractExpansion.naiveGreedyModel_size_ge_pow
#print axioms Pnp4.Frontier.ContractExpansion.pow_le_of_linear_witnessBits
#print axioms Pnp4.Frontier.ContractExpansion.pow_quadratic_gt_poly

#print axioms Pnp3.ComplexityInterfaces.DagCircuit.evalGateAt_congr
#print axioms Pnp3.ComplexityInterfaces.DagCircuit.snocBundleSubst_gates
#print axioms Pnp3.ComplexityInterfaces.DagCircuit.evalOutput_snocBundleSubst_new
#print axioms Pnp3.ComplexityInterfaces.DagCircuit.evalOutput_snocBundleSubst_old

#print axioms Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguage_accepts_iff
#print axioms Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguage_rejects_malformed
#print axioms Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguage_accepts_of_parse_and_witness
#print axioms Pnp4.Frontier.ContractExpansion.tableLen_le_treeMCSPPrefixAmbientLength
#check Pnp4.Frontier.ContractExpansion.RuntimeAwareTreeCircuitCodec
#check Pnp4.Frontier.ContractExpansion.RuntimeAwarePrefixParser
#check Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixRuntimeBudget
#print axioms Pnp4.Frontier.ContractExpansion.bitLength_pos_of_pos
#print axioms Pnp4.Frontier.ContractExpansion.nat_lt_two_pow_bitLength
#print axioms Pnp4.Frontier.ContractExpansion.readNatBE_eq_of_readBit_eq
#print axioms Pnp4.Frontier.ContractExpansion.readNatBE_natBEField_tail
#print axioms Pnp4.Frontier.ContractExpansion.readNatBE_natBEField_zero
#print axioms Pnp4.Frontier.ContractExpansion.be_digit_step
#print axioms Pnp4.Frontier.ContractExpansion.readNatBE_natBEField_slice
#print axioms Pnp4.Frontier.ContractExpansion.gammaBit_zero_prefix
#print axioms Pnp4.Frontier.ContractExpansion.gammaBit_terminator
#print axioms Pnp4.Frontier.ContractExpansion.readNatBE_gammaBit_payload
#print axioms Pnp4.Frontier.ContractExpansion.decodeGammaAux_gammaBit
#print axioms Pnp4.Frontier.ContractExpansion.decodeGamma_gammaBit
#print axioms Pnp4.Frontier.ContractExpansion.decodeGammaAux_gammaBit_from_at
#print axioms Pnp4.Frontier.ContractExpansion.prefixLength_lt_two_pow_idxWidth
#print axioms Pnp4.Frontier.ContractExpansion.tableLen_le_treeMCSPPrefixM
#check Pnp4.Frontier.ContractExpansion.natBEField
#check Pnp4.Frontier.ContractExpansion.CanonicalRawTreeMCSPPrefixFields
#check Pnp4.Frontier.ContractExpansion.encodeTreeMCSPPrefixFields
#check Pnp4.Frontier.ContractExpansion.CanonicalRawTreeMCSPPrefixFields.toPrefixInput
#print axioms Pnp4.Frontier.ContractExpansion.encodeTreeMCSPPrefixFields_length_convention
#print axioms Pnp4.Frontier.ContractExpansion.readNatBE_encode_tag
#print axioms Pnp4.Frontier.ContractExpansion.sliceBits_encode_x
#print axioms Pnp4.Frontier.ContractExpansion.sliceBits_encode_p
#print axioms Pnp4.Frontier.ContractExpansion.parse_encodeTreeMCSPPrefixFields_partial_obligation
#print axioms Pnp4.Frontier.ContractExpansion.parse_encodeTreeMCSPPrefixFields
#print axioms Pnp4.Frontier.ContractExpansion.parseTreeMCSPPrefixInput_bad_tag
#print axioms Pnp4.Frontier.ContractExpansion.parseTreeMCSPPrefixInput_length_convention
#print axioms Pnp4.Frontier.ContractExpansion.parseTreeMCSPPrefixInput_malformed_rejected
#check Pnp4.Frontier.ContractExpansion.treeMCSPConcretePrefixParser
#check Pnp4.Frontier.ContractExpansion.treeMCSPRuntimeAwarePrefixParser

-- Semantic verifier for the prefix-extension language (NP-verifier track, PR 1).
-- Standard axiom set [propext, Classical.choice, Quot.sound] throughout.  The arithmetic /
-- prefix-agreement helpers are Classical-free; the codec-verification path inherits
-- Classical.choice from the pre-existing verifiesDecidable, and the headline equivalence
-- additionally from the classical PrefixExtensionLanguage wrapper.
#print axioms Pnp4.Frontier.ContractExpansion.witnessBits_le_treeMCSPPrefixM
#print axioms Pnp4.Frontier.ContractExpansion.prefixAgreesBool_eq_true_iff
#print axioms Pnp4.Frontier.ContractExpansion.verifiesBool_eq_true_iff
#print axioms Pnp4.Frontier.ContractExpansion.extractWitness_eq
#print axioms Pnp4.Frontier.ContractExpansion.treePrefixSemanticAccepts_rejects_malformed
#print axioms Pnp4.Frontier.ContractExpansion.treePrefixSemanticAccepts_correct

-- Verifier input-tape layout (NP-verifier track, Phase 6); Classical-free.
#print axioms Pnp4.Frontier.ContractExpansion.prefixVerifierInputLen_eq
#print axioms Pnp4.Frontier.ContractExpansion.prefixVerifierWitnessRegion_within_input
#print axioms Pnp4.Frontier.ContractExpansion.concatBitstring_left
#print axioms Pnp4.Frontier.ContractExpansion.concatBitstring_right
#print axioms Pnp4.Frontier.ContractExpansion.verifierTape_left
#print axioms Pnp4.Frontier.ContractExpansion.verifierTape_right
#print axioms Pnp4.Frontier.ContractExpansion.queryPrefixOffset_add_witnessBits
#print axioms Pnp4.Frontier.ContractExpansion.queryPrefixOffset_le
-- Gamma/x field-fit bounds (gamma-decode phase layout preconditions); Classical-free arithmetic.
#print axioms Pnp4.Frontier.ContractExpansion.queryXOffset_le_treeMCSPPrefixM
#print axioms Pnp4.Frontier.ContractExpansion.gammaLen_le_treeMCSPPrefixM
#print axioms Pnp4.Frontier.ContractExpansion.instanceSize_lt_treeMCSPPrefixM
-- Gamma payload-read geometry (§6f scheme); Classical-free arithmetic.
#print axioms Pnp4.Frontier.ContractExpansion.gammaLen_eq_two_mul_gammaZeros_add_one
#print axioms Pnp4.Frontier.ContractExpansion.gammaTermOffset_lt_queryXOffset
#print axioms Pnp4.Frontier.ContractExpansion.gammaTermOffset_le_treeMCSPPrefixM
#print axioms Pnp4.Frontier.ContractExpansion.gammaMirror_mem

-- Bounded-loop primitive (NP-verifier track); Classical-free arithmetic/structural.
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.repeatProgram_timeBound
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.repeatProgram_timeBound_le
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.repeatProgram_run_succ
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.repeatProgram_run_zero
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seqList_timeBound_sum
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seqList_timeBound_le
-- Compositional never-moves-left (head-bound tracking); structural TM reasoning.
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_neverMovesLeft
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.idleCS_neverMovesLeft
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seqList_neverMovesLeft
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seqList_runConfig_head_bounds
-- Single-step seq simulation (P1 region); structural TM reasoning.
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_normal_phase
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_normal_state
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_normal_tape
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_normal_head
-- Handoff + P2-region single-step seq simulation; structural TM reasoning.
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_accept_phase
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_accept_state
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_accept_tape
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P1_accept_head
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P2_phase
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P2_state
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P2_tape
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.seq_stepConfig_P2_head
#print axioms Pnp3.Internal.PsubsetPpoly.TM.PhasedProgram.accepts_toTM
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_transition_move
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_stepConfig_phase
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_stepConfig_head
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_stepConfig_tape
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_stepConfig_state
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_runConfig_scan
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_accepts_eq_state
-- Tag-check semantic characterization (NP-verifier track).  The pure bit/spec lemmas are
-- Classical-free ([propext]); the TM-execution lemmas carry the standard [propext, Classical.choice,
-- Quot.sound] of the rest of the tag-check TM layer (no new axioms beyond the toolkit's).
#print axioms Pnp4.Frontier.ContractExpansion.natBitBE_tag_eq
#print axioms Pnp4.Frontier.ContractExpansion.tagMatchPrefix_succ
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_tape_read
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_runConfig_matched
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_accepts_eq_tagMatch
-- Prop characterization (tagMatchPrefix_eq_true_iff Classical-free; accepts_iff inherits TM triple).
#print axioms Pnp4.Frontier.ContractExpansion.tagMatchPrefix_eq_true_iff
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgram_accepts_iff
-- Unit-state tag check (common-state assembly variant); structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgramU_transition_move
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgramU_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgramU_runConfig_inv
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgramU_accepts_iff
-- Gamma-decode phase, first brick: count-zeros scan structural lemmas; structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_transition_move
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_stepConfig_phase
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_stepConfig_state
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_stepConfig_tape
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_stepConfig_head
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_runConfig_terminator
#print axioms Pnp4.Frontier.ContractExpansion.gammaZeroScanProgram_locates_gamma_terminator
-- M-compatible self-loop scan (back-edge construct); structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_transition_move
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_stepConfig_scan_zero_phase
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_stepConfig_scan_zero_head
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_stepConfig_scan_zero_tape
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_stepConfig_scan_one_head
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_runConfig_terminator
-- Leftward scan-to-marker (first bidirectional primitive).
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeft_stepConfig_scan_zero_head_clamp
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeft_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeft_runConfig_terminator
-- Unary countdown self-loop (marker-free counter).
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopCountdownLeft_runConfig_consume
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopCountdownLeft_runConfig_empty
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopCountdownLeft_seqP2_runConfig_consume
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopCountdownLeft_seqP2_runConfig_empty
-- Bounded body-reentry loop combinator (loop-control single-steps).
#print axioms Pnp4.Frontier.ContractExpansion.repeatBody_stepConfig_consume_phase
#print axioms Pnp4.Frontier.ContractExpansion.repeatBody_stepConfig_halt_phase
#print axioms Pnp4.Frontier.ContractExpansion.repeatBody_stepConfig_handoff_phase
#print axioms Pnp4.Frontier.ContractExpansion.repeatBody_runConfig_one_iteration
#print axioms Pnp4.Frontier.ContractExpansion.repeatBody_runConfig_iterate
#print axioms Pnp4.Frontier.ContractExpansion.repeatBody_runConfig_one_iteration'
#print axioms Pnp4.Frontier.ContractExpansion.repeatBody_runConfig_iterate'
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopFill_runConfig_fill
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopFill_seqP2_runConfig_fill
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeft_seqP2_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeft_seqP2_runConfig_terminator
-- Leftward scan-over-`1`s (bit-dual; completes the four-way scan vocabulary).
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeftOne_stepConfig_scan_one_head_clamp
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeftOne_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeftOne_runConfig_terminator
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeftOne_seqP2_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanLeftOne_seqP2_runConfig_terminator
-- Rightward scan-over-`1`s (pure-traversal fourth scan; marker-free unary-distance seek, §6k).
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanRightOne_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanRightOne_runConfig_terminator
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanRightOne_seqP2_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanRightOne_seqP2_runConfig_terminator
-- Gate-record layout decoder (D0): round-trip + size, expected Classical-free.
#print axioms Pnp4.Frontier.ContractExpansion.decodeUnaryField_unaryField
#print axioms Pnp4.Frontier.ContractExpansion.decodeGateRecord_encodeGateRecord
#print axioms Pnp4.Frontier.ContractExpansion.encodeGateRecord_length
-- Tape-level unary-field reader (D1a): tape↔spec bridge + reader correctness.
#print axioms Pnp4.Frontier.ContractExpansion.tapeReadList_eq_unaryField
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanRightOne_readsUnaryField
#print axioms Pnp4.Frontier.ContractExpansion.decodeUnaryField_tapeReadList_of_reads
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopScanRightOne_readsUnaryField_seqP2
-- Gate-tag dispatcher (D1b part 1): scanning invariant + dispatch run-behaviour.
#print axioms Pnp4.Frontier.ContractExpansion.gateTagDispatch_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.gateTagDispatch_runConfig_dispatch
-- Monolithic one-gate-record decoder (D1b part 2): per-tag traversal + decodeGateRecord correspondence.
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_runConfig_input
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_runConfig_and
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_runConfig_or
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_decodes_input
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_decodes_const
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_decodes_not
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_decodes_and
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_decodes_or
-- D1b part 2 composition: decoder as a non-first seq phase (P2-region).
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_seqP2_runConfig_input
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_seqP2_runConfig_and
#print axioms Pnp4.Frontier.ContractExpansion.gateOneRecordDecoder_seqP2_runConfig_or
-- D2 spec foundation: gate-record stream round-trip + circuit-codec faithfulness bridge.
#print axioms Pnp4.Frontier.ContractExpansion.decodeGateRecordStream_encodeGateRecordStream
#print axioms Pnp4.Frontier.ContractExpansion.decodeGateRecordStream_flatten_eval
#print axioms Pnp4.Frontier.ContractExpansion.decodeGateStream_encodeGateStream
#print axioms Pnp4.Frontier.ContractExpansion.decodeGateStream_circuit_eval
#print axioms Pnp4.Frontier.ContractExpansion.transcodeWitness_faithful
-- Head-advancing self-terminating loop combinator (control structure).
#print axioms Pnp4.Frontier.ContractExpansion.loopUntilSink_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.loopUntilSink_runConfig_oneIter
#print axioms Pnp4.Frontier.ContractExpansion.loopUntilSink_runConfig_halt_stays
#print axioms Pnp4.Frontier.ContractExpansion.runConfig_head_val_ge
#print axioms Pnp4.Frontier.ContractExpansion.runConfig_head_dist_le
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_locates_gamma_terminator
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_runConfig_done
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_run_locates_terminator
-- Self-loop binary increment (variable-width counter machinery); structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_stepConfig_carry_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_stepConfig_stop_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_runConfig_carry
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_runConfig_stop
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_runConfig_counterValue
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_runConfig_done
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_run_counterValue
-- Self-loop binary decrement (dual down-counter step); dual bit-flip arithmetic + structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.counterValue_first_one_diff
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_stepConfig_borrow_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_stepConfig_stop_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_runConfig_borrow
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_runConfig_stop
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_runConfig_counterValue
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_runConfig_done
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_run_counterValue
-- Lifting the self-loop counter into a composition (assembly milestone); structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seq_stepConfig_carry_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seq_stepConfig_stop_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seq_runConfig_carry
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seq_runConfig_stop
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seq_runConfig_counterValue
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seq_stepConfig_handoff_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seq_runConfig_handoff
-- Lifting the self-loop gamma scan into a composition (assembly milestone); structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seq_stepConfig_scan_zero_tape
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seq_stepConfig_scan_one_tape
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seq_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seq_runConfig_terminator
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seq_runConfig_handoff
-- Gamma scan in the P2 region (non-first phase).
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seqP2_stepConfig_scan_zero_tape
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seqP2_runConfig_scanning
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seqP2_runConfig_terminator
#print axioms Pnp4.Frontier.ContractExpansion.gammaSelfLoopScan_seqNested_runConfig_scanning
-- Decrement composition lift (down-counter survives seq).
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_seq_runConfig_borrow
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_seq_runConfig_stop
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_seq_runConfig_counterValue
-- Increment as a non-first (P2-region) phase, arbitrary start; structural TM reasoning.
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seqP2_stepConfig_carry_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seqP2_stepConfig_stop_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seqP2_runConfig_carry
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seqP2_runConfig_stop
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopIncrement_seqP2_runConfig_counterValue
-- Decrement as a non-first (P2-region) phase, arbitrary start.
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_seqP2_stepConfig_borrow_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_seqP2_stepConfig_stop_tape
#print axioms Pnp4.Frontier.ContractExpansion.selfLoopDecrement_seqP2_runConfig_borrow
-- State lifting + heterogeneous-state skeleton composition (assembly milestone).
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.liftUnitProgram_neverMovesLeft
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.liftUnitProgram_stepConfig_phase
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.liftUnitProgram_stepConfig_state
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.liftUnitProgram_stepConfig_tape
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.toTM_stepConfig_phase
#print axioms Pnp3.Internal.PsubsetPpoly.TM.ConstStatePhasedProgram.toTM_stepConfig_tape
#print axioms Pnp4.Frontier.ContractExpansion.mSkeletonDemo_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.mSkeletonDemo_timeBound_le
#print axioms Pnp4.Frontier.ContractExpansion.mSkeletonU_neverMovesLeft
#print axioms Pnp4.Frontier.ContractExpansion.mSkeletonU_timeBound_le
#print axioms Pnp4.Frontier.ContractExpansion.mSkeletonU_tagCheck_handoff
#print axioms Pnp4.Frontier.ContractExpansion.mSkeletonU_tagCheck_then_scan
-- Tag check run behaviour inside the P1 region of a `seq` (invariant + handoff consumer).
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgramU_seq_runConfig_inv
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckProgramU_seq_runConfig_handoff
-- M's first two leading phases run in sequence on one composed machine.
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckThenGammaScan_runConfig
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckThenGammaScanTerminator_runConfig
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckThenGammaFill_runConfig
#print axioms Pnp4.Frontier.ContractExpansion.tagCheckThenNestedGammaScan_runConfig
