import Complexity.Uniform.V1.PairEncoding

/-!
# Structural language of the fixed pair parser

This module deliberately defines the accepted language without referring to a
Turing machine or to `decodePairList`.  It gives both a three-phase DFA and an
inductive grammar.  The final section proves that these independent semantics
agree with the pre-existing list and indexed decoders.
-/

namespace Pnp3.Complexity.Uniform.V1.FixedPairParser

open PairEncoding

/-- The independent DFA phases.  A `true` is a separator only in `needTag`;
in `needData` it is an ordinary data bit. -/
inductive GrammarPhase where
  | needTag
  | needData
  | witness
  deriving DecidableEq, Repr

/-- One transition of the independent grammar DFA. -/
def grammarStep : GrammarPhase → Bool → GrammarPhase
  | .needTag, false => .needData
  | .needTag, true => .witness
  | .needData, _ => .needTag
  | .witness, _ => .witness

/-- Run the grammar DFA from an explicitly supplied phase. -/
def grammarRun : GrammarPhase → List Bool → GrammarPhase
  | q, [] => q
  | q, b :: rest => grammarRun (grammarStep q b) rest

@[simp] private theorem grammarRun_witness (l : List Bool) :
    grammarRun .witness l = .witness := by
  induction l with
  | nil => rfl
  | cons b rest ih =>
      cases b <;> simpa [grammarRun, grammarStep] using ih

/-- DFA runs compose over list append. -/
theorem grammarRun_append (q : GrammarPhase) (left right : List Bool) :
    grammarRun q (left ++ right) = grammarRun (grammarRun q left) right := by
  induction left generalizing q with
  | nil => rfl
  | cons b rest ih =>
      simp only [List.cons_append, grammarRun]
      exact ih (grammarStep q b)

/-- Boolean acceptance of the independent DFA. -/
def syntaxOK (l : List Bool) : Bool :=
  match grammarRun .needTag l with
  | .witness => true
  | _ => false

@[simp] private theorem syntaxOK_nil : syntaxOK [] = false := rfl

@[simp] private theorem syntaxOK_true (rest : List Bool) :
    syntaxOK (true :: rest) = true := by
  simp [syntaxOK, grammarRun, grammarStep]

@[simp] private theorem syntaxOK_false_nil : syntaxOK [false] = false := rfl

@[simp] private theorem syntaxOK_false_data (b : Bool) (rest : List Bool) :
    syntaxOK (false :: b :: rest) = syntaxOK rest := rfl

/-- Independent structural grammar: zero or more `(false,data)` pairs,
followed by one `true` separator and an arbitrary witness suffix. -/
inductive MergedPairGrammar : List Bool → Prop where
  | delimiter (ws : List Bool) : MergedPairGrammar (true :: ws)
  | tagged (b : Bool) {rest : List Bool} :
      MergedPairGrammar rest → MergedPairGrammar (false :: b :: rest)

/-- Structural grammar completeness of the DFA. -/
private theorem syntaxOK_complete {l : List Bool} (h : MergedPairGrammar l) :
    syntaxOK l = true := by
  induction h with
  | delimiter ws => exact syntaxOK_true ws
  | tagged b h ih => simpa only [syntaxOK_false_data] using ih

/-- Structural grammar soundness of the DFA. -/
private theorem syntaxOK_sound : ∀ l : List Bool,
    syntaxOK l = true → MergedPairGrammar l
  | [], h => by
      simp at h
  | true :: rest, _ => MergedPairGrammar.delimiter rest
  | false :: [], h => by
      simp at h
  | false :: b :: rest, h => by
      apply MergedPairGrammar.tagged b
      apply syntaxOK_sound rest
      simpa only [syntaxOK_false_data] using h

theorem syntaxOK_iff_grammar (l : List Bool) :
    syntaxOK l = true ↔ MergedPairGrammar l :=
  ⟨syntaxOK_sound l, syntaxOK_complete⟩

/-- Every encoder output is generated by the independent grammar. -/
private theorem mergedPairGrammar_encodePairList (xs ws : List Bool) :
    MergedPairGrammar (encodePairList xs ws) := by
  induction xs with
  | nil =>
      simpa [encodePairList, tagList] using MergedPairGrammar.delimiter ws
  | cons b xs ih =>
      simpa [encodePairList, tagList] using MergedPairGrammar.tagged b ih

/-- Every word generated by the independent grammar has the encoder shape. -/
private theorem mergedPairGrammar_eq_encodePairList {l : List Bool}
    (h : MergedPairGrammar l) :
    ∃ xs ws, l = encodePairList xs ws := by
  induction h with
  | delimiter ws =>
      exact ⟨[], ws, by simp [encodePairList, tagList]⟩
  | tagged b h ih =>
      rcases ih with ⟨xs, ws, rfl⟩
      exact ⟨b :: xs, ws, by simp [encodePairList, tagList]⟩

theorem mergedPairGrammar_iff_encodePairList (l : List Bool) :
    MergedPairGrammar l ↔ ∃ xs ws, l = encodePairList xs ws := by
  constructor
  · exact mergedPairGrammar_eq_encodePairList
  · rintro ⟨xs, ws, rfl⟩
    exact mergedPairGrammar_encodePairList xs ws

/-- The independent DFA and the pre-existing structural list decoder agree. -/
private theorem syntaxOK_eq_decodePairList_isSome : ∀ l : List Bool,
    syntaxOK l = (decodePairList l).isSome
  | [] => rfl
  | true :: rest => by simp [decodePairList]
  | false :: [] => rfl
  | false :: b :: rest => by
      rw [syntaxOK_false_data]
      cases h : decodePairList rest with
      | none =>
          simpa [decodePairList, h] using
            (syntaxOK_eq_decodePairList_isSome rest)
      | some p =>
          rcases p with ⟨xs, ws⟩
          simpa [decodePairList, h] using
            (syntaxOK_eq_decodePairList_isSome rest)

/-- Unfolding the dependent decoder changes only the packaging of a successful
list result, not whether a result exists. -/
private theorem decodePair_isSome_eq_decodePairList_isSome {N : Nat}
    (y : Bitstring N) :
    (decodePair y).isSome = (decodePairList (List.ofFn y)).isSome := by
  cases h : decodePairList (List.ofFn y) with
  | none => simp [decodePair, h]
  | some p =>
      rcases p with ⟨xs, ws⟩
      simp [decodePair, h]

/-- Required indexed bridge: independent DFA semantics after `List.ofFn` is
exactly successful dependent decoding. -/
theorem syntaxOK_ofFn_eq_decodePair_isSome {N : Nat}
    (y : Bitstring N) :
    syntaxOK (List.ofFn y) = (decodePair y).isSome := by
  calc
    syntaxOK (List.ofFn y) =
        (decodePairList (List.ofFn y)).isSome :=
      syntaxOK_eq_decodePairList_isSome _
    _ = (decodePair y).isSome :=
      (decodePair_isSome_eq_decodePairList_isSome y).symm

/-- Propositional (rather than merely Boolean) form of the indexed bridge. -/
theorem syntaxOK_ofFn_iff_decodePair_some {N : Nat}
    (y : Bitstring N) :
    syntaxOK (List.ofFn y) = true ↔
      ∃ p : DecodedPair, decodePair y = some p := by
  rw [syntaxOK_ofFn_eq_decodePair_isSome]
  cases h : decodePair y with
  | none => simp
  | some p => simp

/-- Direct propositional bridge from the independent structural grammar to
successful dependent decoding after `List.ofFn`. -/
theorem mergedPairGrammar_ofFn_iff_decodePair_some {N : Nat}
    (y : Bitstring N) :
    MergedPairGrammar (List.ofFn y) ↔
      ∃ p : DecodedPair, decodePair y = some p := by
  calc
    MergedPairGrammar (List.ofFn y) ↔
        syntaxOK (List.ofFn y) = true :=
      (syntaxOK_iff_grammar _).symm
    _ ↔ ∃ p : DecodedPair, decodePair y = some p :=
      syntaxOK_ofFn_iff_decodePair_some y

end Pnp3.Complexity.Uniform.V1.FixedPairParser
