import Lake
open Lake DSL

package pnp3

require mathlib from git "https://github.com/leanprover-community/mathlib4" @ "v4.22.0-rc2"
require fact_locality_lift from "./Facts/LocalityLift"
require fact_sunflower from "./Facts/Sunflower"

@[default_target]
lean_lib PnP3 where
  srcDir := "pnp3"
  globs := #[
    Glob.one `Core.BooleanBasics,
    Glob.one `Core.PDTPartial,
    Glob.one `Core.PDT,
    Glob.one `Core.Atlas,
    Glob.one `Core.SAL_Core,
    Glob.one `Core.ShrinkageWitness,
    Glob.one `Counting.BinomialBounds,
    Glob.one `Counting.CapacityGap,
    Glob.one `Counting.Count_EasyFuncs,
    Glob.one `Counting.CircuitCounting,
    Glob.one `Counting.ShannonCounting,
    Glob.one `Counting.Atlas_to_LB_Core,
    Glob.one `AC0.Formulas,
    -- Multi-switching core: include the shared restriction model plus
    -- the canonical trace helper so downstream modules can import it
    -- without missing `.olean` artifacts.
    Glob.one `AC0.MultiSwitching.Restrictions,
    Glob.one `AC0.MultiSwitching.Duality,
    Glob.one `AC0.MultiSwitching.Definitions,
    Glob.one `AC0.MultiSwitching.BadEvents,
    Glob.one `AC0.MultiSwitching.CanonicalTrace,
    Glob.one `AC0.MultiSwitching.CanonicalDT,
    -- Parameter block for Step 3.2 numerics/encodings.
    Glob.one `AC0.MultiSwitching.Params,
    Glob.one `AC0.MultiSwitching.Numerics,
    Glob.one `AC0.MultiSwitching.Trace,
    Glob.one `AC0.MultiSwitching.TraceBridge,
    Glob.one `AC0.MultiSwitching.CommonBad,
    Glob.one `AC0.MultiSwitching.EncodingCommon,
    Glob.one `AC0.MultiSwitching.CommonBad_Func,
    Glob.one `AC0.MultiSwitching.EncodingCommon_Func,
    Glob.one `AC0.MultiSwitching.Decides,
    Glob.one `AC0.MultiSwitching.Atoms,
    Glob.one `AC0.MultiSwitching.FuncCNF,
    Glob.one `AC0.MultiSwitching.DecidesAtoms,
    Glob.one `AC0.MultiSwitching.CommonCCDT_Func,
    Glob.one `AC0.MultiSwitching.CommonCCDT,
    Glob.one `AC0.MultiSwitching.Counting,
    Glob.one `AC0.MultiSwitching.Encoding,
    Glob.one `AC0.MultiSwitching.ShrinkageFromGood,
    Glob.one `AC0.MultiSwitching.Main,
    Glob.one `Complexity.Promise,
    Glob.one `Complexity.Interfaces,
    Glob.one `Complexity.DagCompose,
    Glob.one `Complexity.PsubsetPpolyInternal.Bitstring,
    Glob.one `Complexity.TMVerifier.GapMCSPVerifier,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringEncoding,
    Glob.one `Complexity.TMVerifier.TuringToolkit.Foundation,
    Glob.one `Complexity.TMVerifier.TuringToolkit.BinaryCounter,
    Glob.one `Complexity.TMVerifier.TuringToolkit.Encoding,
    Glob.one `Complexity.TMVerifier.TuringToolkit.AtomicPrograms,
    Glob.one `Complexity.TMVerifier.TuringToolkit.UnaryAtOffset,
    Glob.one `Complexity.TMVerifier.TuringToolkit.CopyAtOffset,
    Glob.one `Complexity.TMVerifier.TuringToolkit.CombineAtOffset,
    Glob.one `Complexity.TMVerifier.TuringToolkit.GateWrappers,
    Glob.one `Complexity.TMVerifier.TuringToolkit.ConstStatePhasedProgram,
    Glob.one `Complexity.TMVerifier.TuringToolkit.RowConsistencyCheck,
    Glob.one `Complexity.PsubsetPpolyInternal.CircuitTree,
    Glob.one `Complexity.PsubsetPpolyInternal.StraightLine,
    Glob.one `Complexity.PsubsetPpolyInternal.TreeToStraight,
    Glob.one `Complexity.PsubsetPpolyInternal.StraightLineBuilder,
    Glob.one `Complexity.PsubsetPpolyInternal.StraightLineSemantics,
    Glob.one `Complexity.PsubsetPpolyInternal.Simulation,
    Glob.one `Complexity.PsubsetPpolyInternal.ComplexityInterfaces,
    Glob.one `Complexity.PpolyDAG_StraightLineCore,
    Glob.one `Complexity.PpolyDAG_from_StraightLine,
    Glob.one `Complexity.PpolyFormula_from_PpolyDAG_FixedSlice,
    Glob.one `Complexity.PsubsetPpolyDAG_Internal,
    Glob.one `Complexity.Simulation.TM_Encoding,
    Glob.one `Complexity.Simulation.Circuit_Compiler,
    Glob.one `Barrier.Relativization,
    Glob.one `Barrier.NaturalProofs,
    Glob.one `Barrier.Algebrization,
    Glob.one `Barrier.Bypass,
    Glob.one `Models.PartialTruthTable,
    Glob.one `Models.Model_PartialMCSP,
    Glob.one `LowerBounds.LB_Formulas,
    Glob.one `LowerBounds.ApproxClassContradiction,
    Glob.one `LowerBounds.ApproxClassNoGo,
    Glob.one `LowerBounds.SingletonProvenanceEndpoint,
    Glob.one `LowerBounds.SingletonDensityEndpoint,
    Glob.one `LowerBounds.SingletonDensityContradiction,
    Glob.one `LowerBounds.AcceptedFamilyBarrier,
    Glob.one `LowerBounds.DAGStableRestrictionProducer,
    Glob.one `LowerBounds.RouteBSourceClosure,
    Glob.one `LowerBounds.FailedRoute_FixedSliceSupportHalfCore,
    Glob.one `LowerBounds.FailedRoute_FixedSliceSupportHalfImpossible,
    Glob.one `LowerBounds.FailedRoute_GapSliceFamilyVacuous,
    Glob.one `LowerBounds.FailedRoute_EventualTableForceSlackObstruction,
    Glob.one `LowerBounds.FailedRoutes,
    Glob.one `LowerBounds.DAGUnconditionalBlocker,
    Glob.one `LowerBounds.AsymptoticDAGBarrierInterfaces,
    Glob.one `LowerBounds.AsymptoticDAGBarrierTheorems,
    Glob.one `LowerBounds.AsymptoticDAGBarrier,
    Glob.one `LowerBounds.MCSPGapLocality,
    Glob.one `LowerBounds.AntiChecker_Partial,
    Glob.one `LowerBounds.LB_Formulas_Core_Partial,
    Glob.one `LowerBounds.AC0_GapMCSP_Final,
    Glob.one `LowerBounds.AC0_GapMCSP,
    Glob.one `Magnification.LocalityInterfaces_Partial,
    Glob.one `Magnification.Facts_Magnification_Partial,
    Glob.one `Magnification.PipelineStatements_Partial,
    Glob.one `Magnification.AC0LocalityBridge,
    Glob.one `Magnification.AC0AtlasBridge,
    Glob.one `Magnification.AC0ApproxFamilyBridge,
    Glob.one `Magnification.LocalityProvider_Partial,
    Glob.one `Magnification.LocalityLift_Partial,
    Glob.one `Magnification.Bridge_to_Magnification_Partial,
    Glob.one `Magnification.AsymptoticFormulaCollapse,
    Glob.one `Magnification.FinalResultMainline,
    Glob.one `Magnification.FinalResultAuditRoutes,
    Glob.one `Magnification.FinalResultWeakRoutes,
    Glob.one `Magnification.FinalResultLegacyTM,
    Glob.one `Magnification.FinalResultCore,
    Glob.one `Magnification.UnconditionalResearchGap,
    Glob.one `Magnification.CanonicalAsymptoticTrackData,
    Glob.one `Magnification.CanonicalAsymptoticDecider,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_gpt55.MatrixPrimitives,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_gpt55.ToySeparation,
    Glob.one `Magnification.FinalResult,
    -- Research Governance v0.1, PR 4a: refuted-predicate registry.
    Glob.one `RefutedPredicates.Registry,
    -- Research Governance v0.1, PR 10: FrozenSpec stage 1.
    Glob.one `Spec.FrozenSpec,
    -- Research Governance v0.1, FP-1: FixedParams Probe audit surface.
    Glob.one `Magnification.AuditRoutes.FixedParamsProbe,
    -- v0.4.2 Track A-CL0: CrossLength coherence audit target surface
    -- (research objectives only; no theorems, no NoGoLog entry).
    Glob.one `Magnification.AuditRoutes.CrossLengthCoherence_NoGo,
    -- v0.4.3-followup: 10-engineer parallel attack on FP-3b.2.
    -- Triage wiring; final selection happens at S11 integration.
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.Width_NatLog2,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.Width_PowOfTwoSlice,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.RenameSize,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.RenameSupport,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.TTFormulaSizeBound,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.Family_NatLog2,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.Family_PowOfTwoSlice,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.Diversity_BelowN,
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.Diversity_Unbounded,
    -- v0.4.3-followup S11 integration: composition of the parallel
    -- engineer outputs into logWidthAdversary_satisfies_diversity.
    Glob.one `Magnification.AuditRoutes.LogWidthAdversary.Composition,
    -- fp3b4 support-cardinality barrier (post-NOGO-000006 follow-up).
    -- T1..T6 of the 6-slot decomposition, ending in the T6 application.
    Glob.one `Magnification.AuditRoutes.SupportCardinalityBarrier.CanonicalHardwiringFamily,
    Glob.one `Magnification.AuditRoutes.SupportCardinalityBarrier.CanonicalHardwiringSupport,
    Glob.one `Magnification.AuditRoutes.SupportCardinalityBarrier.CanonicalHardwiringWitness,
    Glob.one `Magnification.AuditRoutes.SupportCardinalityBarrier.SupportCardinalityOnly,
    Glob.one `Magnification.AuditRoutes.SupportCardinalityBarrier.Barrier,
    Glob.one `Magnification.AuditRoutes.SupportCardinalityBarrier.InSupportFunctionalDiversityApplication,
    -- fp3b3 ProvenanceFilter v2 design — Phase 1 paper sketches
    -- (4 directions, single engineer handle gpt55).
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.Sketch,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.Filter,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.ExcludesOverbroad,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.ExcludesPrefixAnd,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.ExcludesArbitraryPayload,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.NonVacuity,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.NotSupportCardinalityOnly,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.Survivor,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.AdversarialRobustness.RewriteAttack,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_gpt55.NaturalProofsSelfTest.RepresentationSensitivity,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_A_NormaliseMetaBarrier.Barrier,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_B_gpt55.Sketch,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_C_GPT55.Sketch,
    Glob.one `Magnification.AuditRoutes.ProvenanceFilterV2.V2_D_GPT55.Sketch,
    -- fp3b2 arbitrary-payload strengthening (post-NOGO-000005 follow-up).
    -- T1..T6 of the 6-slot decomposition, ending in the composition theorem.
    Glob.one `Magnification.AuditRoutes.ArbitraryLogWidthTT.AllEssential,
    Glob.one `Magnification.AuditRoutes.ArbitraryLogWidthTT.TTFormulaSupport,
    Glob.one `Magnification.AuditRoutes.ArbitraryLogWidthTT.RenamePayload,
    Glob.one `Magnification.AuditRoutes.ArbitraryLogWidthTT.Family,
    Glob.one `Magnification.AuditRoutes.ArbitraryLogWidthTT.Witness,
    Glob.one `Magnification.AuditRoutes.ArbitraryLogWidthTT.Composition,
    -- fp3b6 distinguisher-matrix provenance audit route (D1/D3 gpt55 + D2 codex,
    -- D4 read-set locality).
    -- (`V_gpt55.MatrixPrimitives` is already declared above, near `FinalResult`.)
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_gpt55.AntiCollapse,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_codex.ToySeparation,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_codexd3a.AntiCollapsePrime,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_codexd3c.Sharpness,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_locality_d4.ReadSetLocality,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_locality_d5.LocalGateInvariance,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_locality_d6.PayloadBudgetThreshold,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_locality_d7.DelocalizationCriterion,
    Glob.one `ThirdPartyFacts.Facts_Switching,
    -- Partial-track bibliography/lemmas used by final magnification result.
    Glob.one `ThirdPartyFacts.PartialTransport,
    Glob.one `ThirdPartyFacts.PartialLocalityLift,
    Glob.one `ThirdPartyFacts.PpolyFormula,
    Glob.one `ThirdPartyFacts.LeafBudget,
    Glob.one `Tests.BarrierAudit,
    Glob.one `Tests.BarrierBypassAudit,
    Glob.one `Tests.AxiomsAudit,
    Glob.one `Tests.AC0PublishableSurface,
    Glob.one `Tests.BridgeLocalityRegression,
    Glob.one `Tests.CanonicalIntegrationTests,
    Glob.one `Tests.RouteSurfaceAudit,
    Glob.one `Tests.CircuitCountTraceBoundProbe,
    Glob.one `Tests.HInDagTrivialityProbe,
    Glob.one `Tests.GlobalHInDagContractProbe,
    Glob.one `Tests.GeneralIsoStrongNoGoProbe,
    Glob.one `Tests.GeneralIsoStrongRouteClosure,
    Glob.one `Tests.PromiseRouteConclusionProbe,
    Glob.one `Tests.WeakRouteSurfaceTests,
    Glob.one `Tests.FormulaSupportBoundsFalsifiabilityProbe,
    Glob.one `Tests.SmokeTests,
    Glob.one `Tests.UnitTests,
    -- Research Governance v0.1, PR 11: target-lock compile-time probe.
    Glob.one `Tests.TargetLockProbe,
    -- Research Governance v0.1, FP-1: FixedParams Probe NoGo smoke skeleton.
    Glob.one `Tests.FixedParams_Probe_NoGo,
    -- v0.4.2 Track A-CL0: regression smoke for the CL-0 target surface.
    Glob.one `Tests.AuditRoutes_CL0_NoGo_Regression,
    -- v0.4.3-followup S11: regression smoke for the log-width adversary
    -- composition + the parallel-engineer outputs it consumes.
    Glob.one `Tests.AuditRoutes_LogWidthAdversary_Smoke,
    Glob.one `Tests.AuditRoutes_ArbitraryLogWidthTT_Smoke,
    Glob.one `Tests.AuditRoutes_SupportCardinalityBarrier_Smoke,
    -- fp3b3.1 + fp3b3.2: smoke for V2-A landing artifacts
    -- (representation-sensitivity self-test + rewrite attack).
    Glob.one `Tests.AuditRoutes_V2A_LandingArtifacts_Smoke
  ]

lean_lib Pnp4 where
  srcDir := "pnp4"
  globs := #[
    Glob.one `Pnp4.AlgorithmsToLowerBounds.BasicCircuitClasses,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.Growth,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.SuperPolynomialBridge,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pSuperPolynomialBridge,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AsymptoticSizeLowerBound,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pAsymptoticBridge,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.TruthTableMCSP,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.LocalPRG,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.CoinProblem,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.CoinMaskingTranslation,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSPCoinReduction,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pCoinLowerBound,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSPCoinReductionContract,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_AC0p_Final,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_AC0p_Quantitative,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pCoinAsymptotic,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_LocalPRG_Transfer,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.LocalPRGHardnessSpec,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.FormulaCircuitTargetModel,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.FormulaCircuitPublishedLowerBound,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_Formula_Final,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_Formula_Theorem2Quantitative,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.FormulaCircuitAsymptotic,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.BridgeToPpolyDAG,
    Glob.one `Pnp4.Frontier.PvsNPBridgeRequirements,
    Glob.one `Pnp4.Frontier.CompressionMagnification,
    Glob.one `Pnp4.Frontier.SearchMCSPMagnification,
    Glob.one `Pnp4.Frontier.SearchMCSPConcreteTargets,
    Glob.one `Pnp4.Frontier.ContractExpansion.C_DAG_Adapter,
    Glob.one `Pnp4.Frontier.ContractExpansion.QueryComposition,
    Glob.one `Pnp4.Frontier.ContractExpansion.QueryBuilder,
    Glob.one `Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguage,
    Glob.one `Pnp4.Frontier.ContractExpansion.PrefixQueryBuilder,
    Glob.one `Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguageNP,
    Glob.one `Pnp4.Frontier.ContractExpansion.PrefixExtensionLanguageRuntime,
    Glob.one `Pnp4.Frontier.ContractExpansion.PrefixParserConvention,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixSerializer,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixQueryCircuits,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPZeroPrefixBuilder,
    Glob.one `Pnp4.Frontier.ContractExpansion.NaiveGreedySizeSpike,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixStateQueryCircuits,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyBundleStep,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyBundleFold,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyOutputCircuits,
    Glob.one `Pnp4.Frontier.ContractExpansion.PrefixExtendableSplit,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPTrueExtensionQuery,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyExtendable,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGreedyTrueOutputCircuits,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPDeciderCorrect,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGreedySolves,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBoundedSolver,
    Glob.one `Pnp4.Frontier.ContractExpansion.BoundedSolverFromPpoly,
    Glob.one `Pnp4.Frontier.ContractExpansion.NoSolverContrapositive,
    Glob.one `Pnp4.Frontier.ContractExpansion.ExtractedScheduleGrowth,
    Glob.one `Pnp4.Frontier.ContractExpansion.ConditionalVerifiedSource,
    Glob.one `Pnp4.Frontier.ContractExpansion.WitnessGrowthReduction,
    Glob.one `Pnp4.Frontier.ContractExpansion.PrefixExtensionNPWitness,
    Glob.one `Pnp4.Frontier.ContractExpansion.ExplicitConditionalSource,
    Glob.one `Pnp4.Frontier.ContractExpansion.ConcreteCodecGap,
    Glob.one `Pnp4.Frontier.ContractExpansion.CircuitTreeBridge,
    Glob.one `Pnp4.Frontier.ContractExpansion.CircuitEncodingLength,
    Glob.one `Pnp4.Frontier.ContractExpansion.CircuitDecodeDepthFree,
    Glob.one `Pnp4.Frontier.ContractExpansion.ConcreteTreeCodec,
    Glob.one `Pnp4.Frontier.ContractExpansion.ConcreteTreeCodecSource,
    Glob.one `Pnp4.Frontier.ContractExpansion.ThresholdGrowth,
    Glob.one `Pnp4.Frontier.ContractExpansion.ConsolidatedTreeSeparation,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixSemanticVerifier,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPPrefixVerifierLayout,
    Glob.one `Pnp4.Frontier.ContractExpansion.BoundedLoopProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.PhasedProgramAccepts,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPTagCheckProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPTagCheckUnit,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGammaScanProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGammaFillProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGammaFillComposition,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPScanLeftProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPScanLeftOneProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPScanRightOneProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPStepRightProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGateRecordLayout,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPUnaryFieldReader,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGateTagDispatch,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGateRecordDecoder,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGateStreamLayout,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGateStreamDecoder,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPGateStreamReachesSink,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPTreeTagDispatch,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPCountdownLeft,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPRepeatBody,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPLoopUntilSink,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBidirHeadBounds,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPSelfLoopCounter,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPUnaryAppendProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPUnaryAppendLeftProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPStepLeftProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPSeekHomeProgram,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPCounterComposition,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryBody,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryMeasure,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroTest,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroFullScan,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroFullScanComposition,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroFullScanNested,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScan,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanPeel,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanBodyBridge,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanBodyStep,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanBodyRun,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanMeasure,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanHstep,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPCounterLowestBit,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPCounterDecodeFin,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanReachesSink,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanOutput,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanScan,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanHbase,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanPos,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanStep2,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopFullScanSeek,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPStepRightBranch,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroRouteRealizable,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroRoute,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroRouteRun,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroRouteRunP1,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroRouteRunCompose,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBZeroRouteRunRealizable,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPSeekHomeAfterRoute,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPSeekHomeAfterRouteRun,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehome,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeRoutePeel,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeHbase,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeDecideFalse,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeHstep,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeSeekHomeRun,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeDecideFalseHead,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeBodyStep,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeBodyRun,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRehomeMeasure,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoop,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopRoutePeel,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopHbase,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopHbaseRealizable,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPBinToUnaryLoopDecideFalse,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPScanComposition,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPTagCheckComposition,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPLeadingPhasesChain,
    Glob.one `Pnp4.Frontier.ContractExpansion.TreeMCSPSkeletonComposition,
    Glob.one `Pnp4.Tests.AlgorithmsToLowerBoundsSurfaceTests,
    Glob.one `Pnp4.Tests.AxiomsAudit
  ]

@[test_driver]
lean_exe test where
  root := `Tests.TestDriver
  srcDir := "pnp3"
