import Lake
open Lake DSL

package pnp3

require mathlib from git "https://github.com/leanprover-community/mathlib4" @ "v4.22.0-rc2"
require fact_locality_lift from "./Facts/LocalityLift"
require fact_sunflower from "./Facts/Sunflower"

@[default_target]
lean_lib PnP3 where
  srcDir := "pnp3"
  globs := #[
    Glob.one `Core.BooleanBasics,
    Glob.one `Core.PDTPartial,
    Glob.one `Core.PDT,
    Glob.one `Core.Atlas,
    Glob.one `Core.SAL_Core,
    Glob.one `Core.ShrinkageWitness,
    Glob.one `Counting.BinomialBounds,
    Glob.one `Counting.CapacityGap,
    Glob.one `Counting.Count_EasyFuncs,
    Glob.one `Counting.CircuitCounting,
    Glob.one `Counting.ShannonCounting,
    Glob.one `Counting.Atlas_to_LB_Core,
    Glob.one `AC0.Formulas,
    -- Multi-switching core: include the shared restriction model plus
    -- the canonical trace helper so downstream modules can import it
    -- without missing `.olean` artifacts.
    Glob.one `AC0.MultiSwitching.Restrictions,
    Glob.one `AC0.MultiSwitching.Duality,
    Glob.one `AC0.MultiSwitching.Definitions,
    Glob.one `AC0.MultiSwitching.BadEvents,
    Glob.one `AC0.MultiSwitching.CanonicalTrace,
    Glob.one `AC0.MultiSwitching.CanonicalDT,
    -- Parameter block for Step 3.2 numerics/encodings.
    Glob.one `AC0.MultiSwitching.Params,
    Glob.one `AC0.MultiSwitching.Numerics,
    Glob.one `AC0.MultiSwitching.Trace,
    Glob.one `AC0.MultiSwitching.TraceBridge,
    Glob.one `AC0.MultiSwitching.CommonBad,
    Glob.one `AC0.MultiSwitching.EncodingCommon,
    Glob.one `AC0.MultiSwitching.CommonBad_Func,
    Glob.one `AC0.MultiSwitching.EncodingCommon_Func,
    Glob.one `AC0.MultiSwitching.Decides,
    Glob.one `AC0.MultiSwitching.Atoms,
    Glob.one `AC0.MultiSwitching.FuncCNF,
    Glob.one `AC0.MultiSwitching.DecidesAtoms,
    Glob.one `AC0.MultiSwitching.CommonCCDT_Func,
    Glob.one `AC0.MultiSwitching.CommonCCDT,
    Glob.one `AC0.MultiSwitching.Counting,
    Glob.one `AC0.MultiSwitching.Encoding,
    Glob.one `AC0.MultiSwitching.ShrinkageFromGood,
    Glob.one `AC0.MultiSwitching.Main,
    Glob.one `Complexity.Promise,
    Glob.one `Complexity.Interfaces,
    Glob.one `Complexity.PsubsetPpolyInternal.Bitstring,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringEncoding,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.Foundation,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.BinaryCounter,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.Encoding,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.AtomicPrograms,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.UnaryAtOffset,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.CopyAtOffset,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.CombineAtOffset,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.GateWrappers,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.ConstStatePhasedProgram,
    Glob.one `Complexity.PsubsetPpolyInternal.TuringToolkit.RowConsistencyCheck,
    Glob.one `Complexity.PsubsetPpolyInternal.CircuitTree,
    Glob.one `Complexity.PsubsetPpolyInternal.StraightLine,
    Glob.one `Complexity.PsubsetPpolyInternal.TreeToStraight,
    Glob.one `Complexity.PsubsetPpolyInternal.StraightLineBuilder,
    Glob.one `Complexity.PsubsetPpolyInternal.StraightLineSemantics,
    Glob.one `Complexity.PsubsetPpolyInternal.Simulation,
    Glob.one `Complexity.PsubsetPpolyInternal.ComplexityInterfaces,
    Glob.one `Complexity.PpolyDAG_StraightLineCore,
    Glob.one `Complexity.PpolyDAG_from_StraightLine,
    Glob.one `Complexity.PpolyFormula_from_PpolyDAG_FixedSlice,
    Glob.one `Complexity.PsubsetPpolyDAG_Internal,
    Glob.one `Complexity.Simulation.TM_Encoding,
    Glob.one `Complexity.Simulation.Circuit_Compiler,
    Glob.one `Barrier.Relativization,
    Glob.one `Barrier.NaturalProofs,
    Glob.one `Barrier.Algebrization,
    Glob.one `Barrier.Bypass,
    Glob.one `Models.PartialTruthTable,
    Glob.one `Models.Model_PartialMCSP,
    Glob.one `LowerBounds.LB_Formulas,
    Glob.one `LowerBounds.ApproxClassContradiction,
    Glob.one `LowerBounds.ApproxClassNoGo,
    Glob.one `LowerBounds.SingletonProvenanceEndpoint,
    Glob.one `LowerBounds.SingletonDensityEndpoint,
    Glob.one `LowerBounds.SingletonDensityContradiction,
    Glob.one `LowerBounds.AcceptedFamilyBarrier,
    Glob.one `LowerBounds.DAGStableRestrictionProducer,
    Glob.one `LowerBounds.RouteBSourceClosure,
    Glob.one `LowerBounds.FailedRoute_FixedSliceSupportHalfCore,
    Glob.one `LowerBounds.FailedRoute_FixedSliceSupportHalfImpossible,
    Glob.one `LowerBounds.FailedRoute_GapSliceFamilyVacuous,
    Glob.one `LowerBounds.FailedRoute_EventualTableForceSlackObstruction,
    Glob.one `LowerBounds.FailedRoutes,
    Glob.one `LowerBounds.RouteNextStep_AcceptedFamily,
    Glob.one `LowerBounds.DAGUnconditionalBlocker,
    Glob.one `LowerBounds.AsymptoticDAGBarrierInterfaces,
    Glob.one `LowerBounds.AsymptoticDAGBarrierTheorems,
    Glob.one `LowerBounds.AsymptoticDAGBarrier,
    Glob.one `LowerBounds.MCSPGapLocality,
    Glob.one `LowerBounds.AntiChecker_Partial,
    Glob.one `LowerBounds.LB_Formulas_Core_Partial,
    Glob.one `LowerBounds.AC0_GapMCSP_Final,
    Glob.one `LowerBounds.AC0_GapMCSP,
    Glob.one `Magnification.LocalityInterfaces_Partial,
    Glob.one `Magnification.Facts_Magnification_Partial,
    Glob.one `Magnification.PipelineStatements_Partial,
    Glob.one `Magnification.AC0LocalityBridge,
    Glob.one `Magnification.AC0AtlasBridge,
    Glob.one `Magnification.AC0ApproxFamilyBridge,
    Glob.one `Magnification.LocalityProvider_Partial,
    Glob.one `Magnification.LocalityLift_Partial,
    Glob.one `Magnification.Bridge_to_Magnification_Partial,
    Glob.one `Magnification.AsymptoticFormulaCollapse,
    Glob.one `Magnification.FinalResultMainline,
    Glob.one `Magnification.FinalResultAuditRoutes,
    Glob.one `Magnification.FinalResultWeakRoutes,
    Glob.one `Magnification.FinalResultLegacyTM,
    Glob.one `Magnification.FinalResultCore,
    Glob.one `Magnification.UnconditionalResearchGap,
    Glob.one `Magnification.AuditRoutes.DistinguisherMatrixProvenance.V_gpt55.MatrixPrimitives,
    Glob.one `Magnification.FinalResult,
    Glob.one `ThirdPartyFacts.Facts_Switching,
    -- Partial-track bibliography/lemmas used by final magnification result.
    Glob.one `ThirdPartyFacts.PartialTransport,
    Glob.one `ThirdPartyFacts.PartialLocalityLift,
    Glob.one `ThirdPartyFacts.PpolyFormula,
    Glob.one `ThirdPartyFacts.LeafBudget,
    Glob.one `Tests.BarrierAudit,
    Glob.one `Tests.BarrierBypassAudit,
    Glob.one `Tests.AxiomsAudit,
    Glob.one `Tests.AC0PublishableSurface,
    Glob.one `Tests.BridgeLocalityRegression,
    Glob.one `Tests.RouteSurfaceAudit,
    Glob.one `Tests.WeakRouteSurfaceTests,
    Glob.one `Tests.FormulaSupportBoundsFalsifiabilityProbe,
    Glob.one `Tests.SmokeTests,
    Glob.one `Tests.UnitTests
  ]

lean_lib Pnp4 where
  srcDir := "pnp4"
  globs := #[
    Glob.one `Pnp4.AlgorithmsToLowerBounds.BasicCircuitClasses,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.Growth,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.SuperPolynomialBridge,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pSuperPolynomialBridge,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AsymptoticSizeLowerBound,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pAsymptoticBridge,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.TruthTableMCSP,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.LocalPRG,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.CoinProblem,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.CoinMaskingTranslation,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSPCoinReduction,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pCoinLowerBound,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSPCoinReductionContract,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_AC0p_Final,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_AC0p_Quantitative,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.AC0pCoinAsymptotic,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_LocalPRG_Transfer,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.LocalPRGHardnessSpec,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.FormulaCircuitTargetModel,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.FormulaCircuitPublishedLowerBound,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_Formula_Final,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.MCSP_Formula_Theorem2Quantitative,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.FormulaCircuitAsymptotic,
    Glob.one `Pnp4.AlgorithmsToLowerBounds.BridgeToPpolyDAG,
    Glob.one `Pnp4.Frontier.PvsNPBridgeRequirements,
    Glob.one `Pnp4.Frontier.CompressionMagnification,
    Glob.one `Pnp4.Frontier.SearchMCSPMagnification,
    Glob.one `Pnp4.Frontier.SearchMCSPConcreteTargets,
    Glob.one `Pnp4.Tests.AlgorithmsToLowerBoundsSurfaceTests,
    Glob.one `Pnp4.Tests.AxiomsAudit
  ]

@[test_driver]
lean_exe test where
  root := `Tests.TestDriver
  srcDir := "pnp3"
