import Mathlib.Tactic

namespace Pnp4
namespace Frontier
namespace OneTapeMagnification

/-!
# Finite unambiguous free binary decision diagrams

This file supplies a finite directed graph model for the read-once branching
programs used by the CLTW route.  Query vertices have their usual Boolean
successors.  `choice` vertices are silent nondeterministic vertices; they are
needed both for an unambiguous selector over a finite component family and for
closure under restrictions.  A decreasing rank makes the graph acyclic.

Walks are oriented forwards.  Consequently a walk from the start to `v`
does not record the query at `v`, while a walk from `v` to the accepting sink
does record it.  This is the convention under which `preVars v` and
`postVars v` agree with the corresponding CLTW sets.
-/

/-- A vertex of a finite branching DAG is either a Boolean query, a silent
nondeterministic choice, or a sink.  The first query successor is taken on
`false` and the second on `true`. -/
inductive FiniteUFBDDNode (n : Nat) (Vertex : Type) where
  | query (queryIndex : Fin n) (ifFalse ifTrue : Vertex)
  | choice (children : List Vertex)
  | sink

namespace FiniteUFBDDNode

/-- The directed child relation generated by a node.  Repeated entries of a
choice list do not create distinct graph edges. -/
def HasChild {n : Nat} {Vertex : Type}
    (node : FiniteUFBDDNode n Vertex) (child : Vertex) : Prop :=
  match node with
  | .query _ ifFalse ifTrue => child = ifFalse ∨ child = ifTrue
  | .choice children => child ∈ children
  | .sink => False

/-- The optional query event contributed when a walk leaves this node. -/
def queryEvent? {n : Nat} {Vertex : Type}
    (node : FiniteUFBDDNode n Vertex) (vertex : Vertex) :
    Option (Vertex × Fin n) :=
  match node with
  | .query queryIndex _ _ => some (vertex, queryIndex)
  | .choice _ => none
  | .sink => none

end FiniteUFBDDNode

/-- A finite acyclic branching graph with a distinguished start and accepting
sink.  Other sinks are rejecting. -/
structure FiniteUnambiguousFBDD (n : Nat) where
  Vertex : Type
  vertexFintype : Fintype Vertex
  vertexDecidableEq : DecidableEq Vertex
  start : Vertex
  accept : Vertex
  node : Vertex → FiniteUFBDDNode n Vertex
  accept_sink : node accept = .sink
  rank : Vertex → Nat
  rank_child : ∀ {source target},
    (node source).HasChild target → rank target < rank source

namespace FiniteUnambiguousFBDD

instance {n : Nat} (B : FiniteUnambiguousFBDD n) : Fintype B.Vertex :=
  B.vertexFintype

instance {n : Nat} (B : FiniteUnambiguousFBDD n) : DecidableEq B.Vertex :=
  B.vertexDecidableEq

/-- Directed graph edges. -/
def Edge {n : Nat} (B : FiniteUnambiguousFBDD n)
    (source target : B.Vertex) : Prop :=
  (B.node source).HasChild target

/-- Every edge strictly decreases the graph rank. -/
theorem rank_lt_of_edge {n : Nat} (B : FiniteUnambiguousFBDD n)
    {source target : B.Vertex} (edge : B.Edge source target) :
    B.rank target < B.rank source :=
  B.rank_child edge

/-- A forward directed walk. -/
inductive Walk {n : Nat} (B : FiniteUnambiguousFBDD n) :
    B.Vertex → B.Vertex → Type where
  | nil (vertex : B.Vertex) : Walk B vertex vertex
  | cons {source middle target : B.Vertex}
      (edge : B.Edge source middle) (tail : Walk B middle target) :
      Walk B source target

namespace Walk

/-- Concatenation of forward walks. -/
def append {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source middle target : B.Vertex} :
    B.Walk source middle → B.Walk middle target → B.Walk source target
  | .nil _, rightWalk => rightWalk
  | .cons edge tail, rightWalk => .cons edge (tail.append rightWalk)

/-- Vertices in forward order, including both endpoints. -/
def vertices {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source target : B.Vertex} : B.Walk source target → List B.Vertex
  | .nil vertex => [vertex]
  | .cons (source := source) _ tail => source :: tail.vertices

/-- Query vertices paired with their queried variables, in chronological
order.  Silent choice vertices contribute no event. -/
def queryEvents {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source target : B.Vertex} :
    B.Walk source target → List (B.Vertex × Fin n)
  | .nil _ => []
  | .cons (source := source) _ tail =>
      ((B.node source).queryEvent? source).toList ++ tail.queryEvents

/-- Variables queried by a walk, in chronological order. -/
def queryTrace {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source target : B.Vertex} (walk : B.Walk source target) : List (Fin n) :=
  walk.queryEvents.map Prod.snd

/-- Query vertices visited by a walk, in chronological order. -/
def queryVertices {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source target : B.Vertex} (walk : B.Walk source target) : List B.Vertex :=
  walk.queryEvents.map Prod.fst

/-- The finite set of variables queried by a walk. -/
def queryVars {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source target : B.Vertex} (walk : B.Walk source target) : Finset (Fin n) :=
  walk.queryTrace.toFinset

@[simp]
theorem queryEvents_append {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source middle target : B.Vertex}
    (leftWalk : B.Walk source middle) (rightWalk : B.Walk middle target) :
    (leftWalk.append rightWalk).queryEvents =
      leftWalk.queryEvents ++ rightWalk.queryEvents := by
  induction leftWalk with
  | nil => simp [append, queryEvents]
  | cons edge tail ih =>
      simp [append, queryEvents, ih, List.append_assoc]

@[simp]
theorem queryTrace_append {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source middle target : B.Vertex}
    (leftWalk : B.Walk source middle) (rightWalk : B.Walk middle target) :
    (leftWalk.append rightWalk).queryTrace =
      leftWalk.queryTrace ++ rightWalk.queryTrace := by
  simp [queryTrace]

@[simp]
theorem queryVars_append {n : Nat} {B : FiniteUnambiguousFBDD n}
    {source middle target : B.Vertex}
    (leftWalk : B.Walk source middle) (rightWalk : B.Walk middle target) :
    (leftWalk.append rightWalk).queryVars =
      leftWalk.queryVars ∪ rightWalk.queryVars := by
  simp [queryVars]

end Walk

/-- An edge is compatible with an input when it follows the corresponding
Boolean successor at a query vertex.  Silent choice edges are all compatible. -/
def CompatibleEdge {n : Nat} (B : FiniteUnambiguousFBDD n)
    (input : Fin n → Bool) (source target : B.Vertex) : Prop :=
  match B.node source with
  | .query queryIndex ifFalse ifTrue =>
      match input queryIndex with
      | false => target = ifFalse
      | true => target = ifTrue
  | .choice children => target ∈ children
  | .sink => False

/-- Compatibility implies that the selected transition is a graph edge. -/
theorem edge_of_compatibleEdge {n : Nat} (B : FiniteUnambiguousFBDD n)
    (input : Fin n → Bool) {source target : B.Vertex}
    (compatible : B.CompatibleEdge input source target) :
    B.Edge source target := by
  cases hnode : B.node source with
  | query queryIndex ifFalse ifTrue =>
      cases hinput : input queryIndex <;>
        simp [CompatibleEdge, Edge, FiniteUFBDDNode.HasChild,
          hnode, hinput] at compatible ⊢
      · exact Or.inl compatible
      · exact Or.inr compatible
  | choice children =>
      simpa [CompatibleEdge, Edge, FiniteUFBDDNode.HasChild, hnode]
        using compatible
  | sink =>
      simp [CompatibleEdge, hnode] at compatible

namespace Walk

/-- Every edge of the walk is compatible with the input. -/
def Compatible {n : Nat} {B : FiniteUnambiguousFBDD n}
    (input : Fin n → Bool) :
    {source target : B.Vertex} → B.Walk source target → Prop
  | _, _, .nil _ => True
  | _, _, .cons (source := source) (middle := middle) _ tail =>
      B.CompatibleEdge input source middle ∧ tail.Compatible input

@[simp]
theorem compatible_append {n : Nat} {B : FiniteUnambiguousFBDD n}
    (input : Fin n → Bool) {source middle target : B.Vertex}
    (leftWalk : B.Walk source middle) (rightWalk : B.Walk middle target) :
    (leftWalk.append rightWalk).Compatible input ↔
      leftWalk.Compatible input ∧ rightWalk.Compatible input := by
  induction leftWalk with
  | nil => simp [append, Compatible]
  | cons edge tail ih => simp [append, Compatible, ih, and_assoc]

end Walk

/-- An accepting input-compatible path. -/
structure AcceptingPath {n : Nat} (B : FiniteUnambiguousFBDD n)
    (input : Fin n → Bool) where
  walk : B.Walk B.start B.accept
  compatible : walk.Compatible input

/-- Existential acceptance semantics. -/
def Accepts {n : Nat} (B : FiniteUnambiguousFBDD n)
    (input : Fin n → Bool) : Prop :=
  Nonempty (B.AcceptingPath input)

/-- Syntactic read-once: every graph path rooted at the start queries each
input variable at most once.  This quantifies over all formal paths, not only
over input-compatible executions. -/
def IsSyntacticallyReadOnce {n : Nat}
    (B : FiniteUnambiguousFBDD n) : Prop :=
  ∀ (target : B.Vertex) (walk : B.Walk B.start target),
    walk.queryTrace.Nodup

/-- Unambiguity: for each input there is at most one compatible accepting
walk. -/
def IsUnambiguous {n : Nat} (B : FiniteUnambiguousFBDD n) : Prop :=
  ∀ (input : Fin n → Bool)
    (left right : B.Walk B.start B.accept),
    left.Compatible input → right.Compatible input → left = right

/-- Variables queried strictly before reaching `vertex`, over all syntactic
start-to-`vertex` paths.  In particular, a query at `vertex` is excluded. -/
noncomputable def preVars {n : Nat} (B : FiniteUnambiguousFBDD n)
    (vertex : B.Vertex) : Finset (Fin n) := by
  classical
  exact Finset.univ.filter fun queryIndex =>
    ∃ walk : B.Walk B.start vertex, queryIndex ∈ walk.queryTrace

/-- Variables queried on a syntactic path from `vertex` to the accepting
sink.  A query at `vertex` is included. -/
noncomputable def postVars {n : Nat} (B : FiniteUnambiguousFBDD n)
    (vertex : B.Vertex) : Finset (Fin n) := by
  classical
  exact Finset.univ.filter fun queryIndex =>
    ∃ walk : B.Walk vertex B.accept, queryIndex ∈ walk.queryTrace

theorem mem_preVars_iff {n : Nat} (B : FiniteUnambiguousFBDD n)
    {vertex : B.Vertex} {queryIndex : Fin n} :
    queryIndex ∈ B.preVars vertex ↔
      ∃ walk : B.Walk B.start vertex, queryIndex ∈ walk.queryTrace := by
  classical
  simp [preVars]

theorem mem_postVars_iff {n : Nat} (B : FiniteUnambiguousFBDD n)
    {vertex : B.Vertex} {queryIndex : Fin n} :
    queryIndex ∈ B.postVars vertex ↔
      ∃ walk : B.Walk vertex B.accept, queryIndex ∈ walk.queryTrace := by
  classical
  simp [postVars]

namespace Walk

/-- Every variable on a start-to-vertex prefix belongs to `preVars`. -/
theorem queryVars_subset_preVars {n : Nat}
    {B : FiniteUnambiguousFBDD n} {vertex : B.Vertex}
    (walk : B.Walk B.start vertex) :
    walk.queryVars ⊆ B.preVars vertex := by
  intro queryIndex hqueryIndex
  rw [B.mem_preVars_iff]
  exact ⟨walk, by simpa [queryVars] using hqueryIndex⟩

/-- Every variable on a vertex-to-accept suffix belongs to `postVars`. -/
theorem queryVars_subset_postVars {n : Nat}
    {B : FiniteUnambiguousFBDD n} {vertex : B.Vertex}
    (walk : B.Walk vertex B.accept) :
    walk.queryVars ⊆ B.postVars vertex := by
  intro queryIndex hqueryIndex
  rw [B.mem_postVars_iff]
  exact ⟨walk, by simpa [queryVars] using hqueryIndex⟩

end Walk

/-- Under syntactic read-once, no variable can occur both before a vertex and
on a continuation from that vertex to acceptance. -/
theorem preVars_disjoint_postVars {n : Nat}
    (B : FiniteUnambiguousFBDD n) (hreadOnce : B.IsSyntacticallyReadOnce)
    (vertex : B.Vertex) :
    Disjoint (B.preVars vertex) (B.postVars vertex) := by
  classical
  rw [Finset.disjoint_left]
  intro queryIndex hpre hpost
  rw [B.mem_preVars_iff] at hpre
  rw [B.mem_postVars_iff] at hpost
  rcases hpre with ⟨leftWalk, hleft⟩
  rcases hpost with ⟨rightWalk, hright⟩
  have hnodup :
      (leftWalk.queryTrace ++ rightWalk.queryTrace).Nodup := by
    simpa using hreadOnce B.accept (leftWalk.append rightWalk)
  have hdisjoint :
      List.Disjoint leftWalk.queryTrace rightWalk.queryTrace :=
    List.disjoint_of_nodup_append hnodup
  exact hdisjoint hleft hright

end FiniteUnambiguousFBDD
end OneTapeMagnification
end Frontier
end Pnp4
