import Mathlib.Tactic
import Pnp4.Frontier.OneTapeMagnification.MandatoryCanonicalSelectorTerminalFactorGraph
import Pnp4.Frontier.OneTapeMagnification.TimedAlphaCanonicalFiberMaskedCorrelation
import Pnp4.Frontier.OneTapeMagnification.FiniteLayeredFamilyComponentDecomposition

namespace Pnp4
namespace Frontier
namespace OneTapeMagnification

/-!
# Block-projection correlation for the mandatory canonical selector

The fixed-alpha rectangle theorem is transported here to the actual mandatory
selector.  Every component indicator is exactly a product of disjoint local
block-projection indicators.  Since the family is unambiguous, the complete
selector is exactly a disjoint sum of those products.  Fixed-mask uniform
averaging then gives a sum of products of local masked correlations.

This is an exact identity for the installed selector, not a component-count
upper bound.  It does not by itself bound the signed cross-alpha Fourier
correlation generated by the structured short seed.
-/

open scoped BigOperators

open FiniteBooleanRestrictionMoment
open FiniteBooleanMaskedProductFactorization
open FiniteBooleanOneRoundFoolingBound

namespace FiniteLayeredQueryProgramFamily

local instance cachedInputMachineStateDecidableEqForBlockProjectionCorrelation
    (machine : DeterministicMachine) [DecidableEq machine.State] :
    DecidableEq (cachedInputMachine machine).State :=
  cachedInputStateDecidableEq machine

/-- One installed mandatory component is exactly the product of its canonical
block projections. -/
theorem mandatoryCanonical_ratComponentAcceptanceIndicator_eq_blockProjectionProduct
    (machine : DeterministicMachine) [DecidableEq machine.State]
    (input : List Bool) (T b : Nat) (hb : 0 < b)
    (index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b)
    :
    let family := mandatoryFiniteRejectingGuardedCanonicalFamily
      machine input.length T b
    let scheduled := builtTimedAlphaVisitSchedule
      (cachedInputMachine machine) index.1
    let candidate := fun coordinate : Fin input.length => input.get coordinate
    family.ratComponentAcceptanceIndicator index candidate =
      ∏ block : Fin (T / b + 1),
        finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
          machine hb index.1 scheduled block candidate := by
  classical
  dsimp only
  let cached := cachedInputMachine machine
  let scheduled := builtTimedAlphaVisitSchedule cached index.1
  let family := mandatoryFiniteRejectingGuardedCanonicalFamily
    machine input.length T b
  let candidate := fun coordinate : Fin input.length => input.get coordinate
  have hevalCheck : (family.program index).eval candidate =
      timedAlphaVisitScheduleInPlaceCanonicalCutCheck
        cached input index.1 scheduled := by
    calc
      (family.program index).eval candidate =
          ((finiteRejectingGuardedCanonicalFamily
            machine input.length T b).program index).eval candidate :=
        mandatoryBuiltRejectingGuardedCanonicalComponent_eval_eq_family
          machine input.length index candidate
      _ = timedAlphaVisitScheduleInPlaceCanonicalCutCheck
          cached input index.1 scheduled := by
        exact
          compileRejectingMasterGuardedFiniteCachedTimedAlphaScheduleAllBlocksInPlaceRollingTotal_eval_eq_inPlaceCanonicalCutCheck
            machine input index.1 scheduled
  change (if (family.program index).eval candidate = true then 1 else 0) = _
  rw [hevalCheck]
  have hproduct :=
    finiteRatPropIndicator_inPlaceCanonicalCutCheck_eq_blockProjectionProduct
      machine hb index.1 scheduled candidate
  have hroundtrip : List.ofFn candidate = input := by
    exact List.ofFn_get input
  rw [hroundtrip] at hproduct
  by_cases hcheck : timedAlphaVisitScheduleInPlaceCanonicalCutCheck
      (cachedInputMachine machine) input index.1
        (builtTimedAlphaVisitSchedule
          (cachedInputMachine machine) index.1) = true
  · simpa [finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor,
      finiteRatPropIndicator, hcheck, cached, scheduled] using hproduct
  · simpa [finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor,
      finiteRatPropIndicator, hcheck, cached, scheduled] using hproduct

/-- The terminal true-prefix indicator of one selector component is the same
block-projection product.  Thus the factorization is available directly at
the selector vertex used by prefix/suffix Fourier cuts. -/
theorem mandatoryCanonicalSelectorMasterEnd_ratCompatiblePrefixIndicator_eq_blockProjectionProduct
    (machine : DeterministicMachine) [DecidableEq machine.State]
    (input : List Bool) (T b : Nat) (hb : 0 < b)
    (index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b)
    :
    let family := mandatoryFiniteRejectingGuardedCanonicalFamily
      machine input.length T b
    let scheduled := builtTimedAlphaVisitSchedule
      (cachedInputMachine machine) index.1
    let candidate := fun coordinate : Fin input.length => input.get coordinate
    (family.selectorFBDD).ratCompatiblePrefixIndicator candidate
        (mandatoryCanonicalSelectorMasterEndTrueVertex
          machine input.length index) =
      ∏ block : Fin (T / b + 1),
        finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
          machine hb index.1 scheduled block candidate := by
  classical
  let family := mandatoryFiniteRejectingGuardedCanonicalFamily
    machine input.length T b
  let scheduled := builtTimedAlphaVisitSchedule
    (cachedInputMachine machine) index.1
  let terminal := mandatoryCanonicalSelectorMasterEndTrueVertex
    machine input.length index
  let candidate := fun coordinate : Fin input.length => input.get coordinate
  have hprefix :=
    mandatoryCanonicalSelectorMasterEnd_hasCompatiblePrefix_iff_eval_true
      machine input.length index candidate
  have hcomponent :=
    mandatoryCanonical_ratComponentAcceptanceIndicator_eq_blockProjectionProduct
      machine input T b hb index
  change (family.selectorFBDD).ratCompatiblePrefixIndicator candidate terminal = _
  have hindicator :
      (family.selectorFBDD).ratCompatiblePrefixIndicator candidate terminal =
        family.ratComponentAcceptanceIndicator index candidate := by
    have hiff : family.selectorFBDD.HasCompatiblePrefix candidate terminal ↔
        (family.program index).eval candidate = true := by
      simpa [family, terminal, candidate] using hprefix
    unfold FiniteUnambiguousFBDD.ratCompatiblePrefixIndicator
      FiniteUnambiguousFBDD.compatiblePrefixIndicator
      ratComponentAcceptanceIndicator
    by_cases hpref : family.selectorFBDD.HasCompatiblePrefix candidate terminal
    · have heval := hiff.1 hpref
      simp [hpref, heval]
    · have heval : (family.program index).eval candidate ≠ true :=
        fun h => hpref (hiff.2 h)
      simp [hpref, heval]
  rw [hindicator]
  simpa [family, scheduled, candidate] using hcomponent

/-- Exact pointwise representation of the whole mandatory selector as an
unambiguous sum of fixed-alpha block products. -/
theorem mandatoryCanonicalSelector_ratAcceptanceIndicator_eq_sum_blockProjectionProducts
    (machine : DeterministicMachine) [DecidableEq machine.State]
    (input : List Bool) (T b : Nat) (hb : 0 < b) :
    let family := mandatoryFiniteRejectingGuardedCanonicalFamily
      machine input.length T b
    let candidate := fun coordinate : Fin input.length => input.get coordinate
    family.selectorFBDD.ratAcceptanceIndicator candidate =
      ∑ index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b,
        ∏ block : Fin (T / b + 1),
          finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
            machine hb index.1
              (builtTimedAlphaVisitSchedule
                (cachedInputMachine machine) index.1)
              block candidate := by
  classical
  dsimp only
  let family := mandatoryFiniteRejectingGuardedCanonicalFamily
    machine input.length T b
  let candidate := fun coordinate : Fin input.length => input.get coordinate
  letI : Fintype family.Index := family.indexFintype
  rw [family.selector_ratAcceptanceIndicator_eq_sum_components
    (mandatoryFiniteRejectingGuardedCanonicalFamily_isUnambiguous
      machine input.length T b hb) candidate]
  apply Finset.sum_congr rfl
  intro index _hindex
  simpa [family, candidate] using
    (mandatoryCanonical_ratComponentAcceptanceIndicator_eq_blockProjectionProduct
      machine input T b hb index)

/-- **Whole-selector fixed-mask correlation identity.**  The exact uniform
conditional mean of the installed mandatory selector is the sum, over its
eligible canonical-alpha components, of products of local block-projection
means.  This is linearity plus the fixed-alpha rectangle theorem; no
lower-bound or pseudorandomness hypothesis is used. -/
theorem mandatoryCanonicalSelector_finiteAverage_maskedInput_eq_sum_projectionProd
    (machine : DeterministicMachine) [DecidableEq machine.State]
    (n T b : Nat) (hb : 0 < b) (base mask : Fin n → Bool) :
    let family := mandatoryFiniteRejectingGuardedCanonicalFamily machine n T b
    finiteAverage (fun uniform : Fin n → Bool =>
        family.selectorFBDD.ratAcceptanceIndicator
          (maskedInput base mask uniform)) =
      ∑ index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b,
        ∏ block : Fin (T / b + 1),
          finiteAverage (fun uniform : Fin n → Bool =>
            finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
              machine hb index.1
                (builtTimedAlphaVisitSchedule
                  (cachedInputMachine machine) index.1)
                block (maskedInput base mask uniform)) := by
  classical
  dsimp only
  let family := mandatoryFiniteRejectingGuardedCanonicalFamily machine n T b
  have hpointwise (candidate : Fin n → Bool) :
      family.selectorFBDD.ratAcceptanceIndicator candidate =
        ∑ index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b,
          ∏ block : Fin (T / b + 1),
            finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
              machine hb index.1
                (builtTimedAlphaVisitSchedule
                  (cachedInputMachine machine) index.1)
                block candidate := by
    let statement : (Σ arity : Nat, Fin arity → Bool) → Prop := fun tuple =>
      (mandatoryFiniteRejectingGuardedCanonicalFamily
          machine tuple.1 T b).selectorFBDD.ratAcceptanceIndicator tuple.2 =
        ∑ index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b,
          ∏ block : Fin (T / b + 1),
            finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
              machine hb index.1
                (builtTimedAlphaVisitSchedule
                  (cachedInputMachine machine) index.1)
                block tuple.2
    have hlist : statement
        (List.equivSigmaTuple (List.ofFn candidate)) := by
      exact
        mandatoryCanonicalSelector_ratAcceptanceIndicator_eq_sum_blockProjectionProducts
          machine (List.ofFn candidate) T b hb
    have hsigma : List.equivSigmaTuple (List.ofFn candidate) =
        (⟨n, candidate⟩ : Σ arity : Nat, Fin arity → Bool) :=
      (List.equivSigmaTuple (α := Bool)).apply_symm_apply ⟨n, candidate⟩
    have htuple : statement
        (⟨n, candidate⟩ : Σ arity : Nat, Fin arity → Bool) :=
      hsigma ▸ hlist
    simpa [statement, family] using htuple
  calc
    finiteAverage (fun uniform : Fin n → Bool =>
        family.selectorFBDD.ratAcceptanceIndicator
          (maskedInput base mask uniform)) =
      finiteAverage (fun uniform : Fin n → Bool =>
        ∑ index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b,
          ∏ block : Fin (T / b + 1),
            finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
              machine hb index.1
                (builtTimedAlphaVisitSchedule
                  (cachedInputMachine machine) index.1)
                block (maskedInput base mask uniform)) := by
      apply finiteAverage_congr
      intro uniform
      exact hpointwise (maskedInput base mask uniform)
    _ = ∑ index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b,
        finiteAverage (fun uniform : Fin n → Bool =>
          ∏ block : Fin (T / b + 1),
            finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
              machine hb index.1
                (builtTimedAlphaVisitSchedule
                  (cachedInputMachine machine) index.1)
                block (maskedInput base mask uniform)) := by
      exact finiteAverage_fintype_sum _
    _ = ∑ index : BuiltRejectingGuardedCanonicalAlphaIndex machine T b,
        ∏ block : Fin (T / b + 1),
          finiteAverage (fun uniform : Fin n → Bool =>
            finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
              machine hb index.1
                (builtTimedAlphaVisitSchedule
                  (cachedInputMachine machine) index.1)
                block (maskedInput base mask uniform)) := by
      apply Finset.sum_congr rfl
      intro index _hindex
      let scheduled := builtTimedAlphaVisitSchedule
        (cachedInputMachine machine) index.1
      calc
        finiteAverage (fun uniform : Fin n → Bool =>
            ∏ block : Fin (T / b + 1),
              finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
                machine hb index.1 scheduled block
                  (maskedInput base mask uniform)) =
          finiteAverage (fun uniform : Fin n → Bool =>
            finiteRatPropIndicator
              (timedAlphaVisitScheduleInPlaceCanonicalCutCheck
                (cachedInputMachine machine)
                (List.ofFn (maskedInput base mask uniform))
                  index.1 scheduled = true)) := by
            apply finiteAverage_congr
            intro uniform
            symm
            simpa [finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor]
              using
                (finiteRatPropIndicator_inPlaceCanonicalCutCheck_eq_blockProjectionProduct
                  machine hb index.1 scheduled
                    (maskedInput base mask uniform))
        _ = ∏ block : Fin (T / b + 1),
            finiteAverage (fun uniform : Fin n → Bool =>
              finiteCachedTimedAlphaCanonicalBlockProjectionRatFactor
                machine hb index.1 scheduled block
                  (maskedInput base mask uniform)) :=
          finiteAverage_inPlaceCanonicalCutCheck_maskedInput_eq_projectionProd
            machine hb index.1 scheduled
              (builtRejectingGuardedCanonicalIndex_chained machine index)
              (builtRejectingGuardedCanonicalIndexMonotone machine index)
              base mask

end FiniteLayeredQueryProgramFamily

end OneTapeMagnification
end Frontier
end Pnp4
