import Mathlib.Data.Fintype.Card
import Mathlib.Data.Finset.Image

namespace Pnp4
namespace Frontier
namespace OneTapeMagnification

/-!
# Finite support-avoidance barrier

For a map `H : Seed → Table`, the predicate `outsideRange H` accepts exactly
the tables outside the image of `H`.  Its executable finite version,
`avoidSupport H`, rejects every generated table.  If the finite seed universe
is strictly smaller than the finite table universe, this predicate accepts at
least one table; in fact it accepts at least
`Fintype.card Table - Fintype.card Seed` tables.

Thus an HSG statement quantified over an unrestricted class of predicates is
impossible: after seeing `H`, that class can contain the predicate avoiding
the entire support of `H`.  A useful HSG theorem must restrict the predicate
class and separately prove that this support-avoiding predicate is in that
class.

When tables are bit strings, a paper-level way to recognize a finite forbidden
support is to store those strings in a trie-shaped read-once branching
program.  This module does not formalize that model and therefore makes no
claim about ROBP width, size, ordering, or uniformity.  The results below are
only the underlying finite counting obstruction, not a circuit lower bound or
mainline progress toward `P ≠ NP`.
-/

/-- A table lies outside the support of `H` when it is not generated by any
seed. -/
def outsideRange {Seed Table : Type*} (H : Seed → Table) (table : Table) : Prop :=
  table ∉ Set.range H

/-- The executable predicate accepting precisely the complement of the finite
support of `H`. -/
def avoidSupport {Seed Table : Type*} [Fintype Seed] [DecidableEq Table]
    (H : Seed → Table) (table : Table) : Bool :=
  decide (table ∉ Set.range H)

@[simp]
theorem avoidSupport_eq_true_iff
    {Seed Table : Type*} [Fintype Seed] [DecidableEq Table]
    (H : Seed → Table) (table : Table) :
    avoidSupport H table = true ↔ outsideRange H table := by
  simp [avoidSupport, outsideRange]

@[simp]
theorem avoidSupport_eq_false_iff
    {Seed Table : Type*} [Fintype Seed] [DecidableEq Table]
    (H : Seed → Table) (table : Table) :
    avoidSupport H table = false ↔ ¬ outsideRange H table := by
  simp [avoidSupport, outsideRange]

/-- Every output of `H` belongs to its range. -/
theorem not_outsideRange_output
    {Seed Table : Type*} (H : Seed → Table) (seed : Seed) :
    ¬ outsideRange H (H seed) := by
  intro hOutside
  exact hOutside ⟨seed, rfl⟩

/-- The support-avoiding predicate rejects every generated table. -/
@[simp]
theorem avoidSupport_output
    {Seed Table : Type*} [Fintype Seed] [DecidableEq Table]
    (H : Seed → Table) (seed : Seed) :
    avoidSupport H (H seed) = false := by
  simp [avoidSupport_eq_false_iff, not_outsideRange_output]

/-- Equivalently, `H` has no seed hitting its own support-avoiding predicate. -/
theorem not_hits_avoidSupport
    {Seed Table : Type*} [Fintype Seed] [DecidableEq Table]
    (H : Seed → Table) :
    ¬ ∃ seed, avoidSupport H (H seed) = true := by
  simp

/-- The accepted tables are exactly the complement of the finite image of
`H`. -/
private theorem avoidSupport_true_tables_eq_sdiff
    {Seed Table : Type*} [Fintype Seed] [Fintype Table]
    [DecidableEq Table] (H : Seed → Table) :
    (Finset.univ.filter fun table => avoidSupport H table = true) =
      (Finset.univ : Finset Table) \ Finset.univ.image H := by
  ext table
  simp [avoidSupport_eq_true_iff, outsideRange]

/-- Exact cardinality of the complement of the finite image of `H`. -/
theorem card_avoidSupport_true_eq
    {Seed Table : Type*} [Fintype Seed] [Fintype Table]
    [DecidableEq Table] (H : Seed → Table) :
    (Finset.univ.filter fun table => avoidSupport H table = true).card =
      Fintype.card Table - (Finset.univ.image H).card := by
  rw [avoidSupport_true_tables_eq_sdiff]
  have hSubset :
      Finset.univ.image H ⊆ (Finset.univ : Finset Table) := by
    intro table _
    exact Finset.mem_univ table
  simpa using Finset.card_sdiff hSubset

/-- The complement of the image has at least `|Table| - |Seed|` elements. -/
theorem card_avoidSupport_true_lower_bound
    {Seed Table : Type*} [Fintype Seed] [Fintype Table]
    [DecidableEq Table] (H : Seed → Table) :
    Fintype.card Table - Fintype.card Seed ≤
      (Finset.univ.filter fun table => avoidSupport H table = true).card := by
  rw [card_avoidSupport_true_eq]
  have hImageCard :
      (Finset.univ.image H).card ≤ Fintype.card Seed := by
    simpa using
      (Finset.card_image_le :
        (Finset.univ.image H).card ≤ (Finset.univ : Finset Seed).card)
  exact Nat.sub_le_sub_left hImageCard (Fintype.card Table)

/-- A strict finite cardinality gap leaves at least one table outside the
range of `H`. -/
theorem exists_outsideRange_of_card_lt
    {Seed Table : Type*} [Fintype Seed] [Fintype Table]
    [DecidableEq Table] (H : Seed → Table)
    (hCard : Fintype.card Seed < Fintype.card Table) :
    ∃ table, outsideRange H table := by
  have hPositive :
      0 < (Finset.univ.filter fun table => avoidSupport H table = true).card := by
    exact lt_of_lt_of_le (Nat.sub_pos_of_lt hCard)
      (card_avoidSupport_true_lower_bound H)
  rcases Finset.card_pos.mp hPositive with ⟨table, hTable⟩
  exact ⟨table, (avoidSupport_eq_true_iff H table).mp (Finset.mem_filter.mp hTable).2⟩

/-- Under the same gap, the support-avoiding predicate is nonempty even though
`H` does not hit it. -/
theorem exists_avoidSupport_eq_true_of_card_lt
    {Seed Table : Type*} [Fintype Seed] [Fintype Table]
    [DecidableEq Table] (H : Seed → Table)
    (hCard : Fintype.card Seed < Fintype.card Table) :
    ∃ table, avoidSupport H table = true := by
  rcases exists_outsideRange_of_card_lt H hCard with ⟨table, hOutside⟩
  exact ⟨table, (avoidSupport_eq_true_iff H table).2 hOutside⟩

end OneTapeMagnification
end Frontier
end Pnp4
