import Magnification.FinalResult
import Tests.BridgeLocalityRegression
import ThirdPartyFacts.Facts_Switching

/-!
  pnp3/Tests/AxiomsAudit.lean

  Тест-аудит: выводим список аксиом, от которых зависят ключевые теоремы.
  Этот файл компилируется вместе с проектом, чтобы случайные зависимости
  (например, от неожиданных внешних аксиом) были заметны сразу.
-/

open Pnp3
open Pnp3.ComplexityInterfaces
open Pnp3.Magnification

-- Итоговые утверждения (формульная сепарация).
#print axioms NP_not_subset_PpolyFormula_final
#print axioms NP_not_subset_PpolyFormula_final_with_provider
#print axioms NP_not_subset_PpolyFormula_final_with_supportBounds
#print axioms NP_not_subset_PpolyFormula_final_with_multiswitching
#print axioms asymptotic_formula_collapse
#print axioms NP_not_subset_PpolyReal_final
#print axioms NP_not_subset_PpolyReal_final_with_provider
#print axioms NP_not_subset_PpolyReal_final_with_supportBounds
#print axioms NP_not_subset_PpolyReal_final_with_multiswitching
#print axioms NP_not_subset_PpolyFormula_from_partial_formulas

-- Мост от нижних оценок к `NP ⊄ PpolyFormula`.
#print axioms NP_not_subset_PpolyReal_from_partial_formulas
#print axioms OPS_trigger_formulas_partial_of_provider
#print axioms OPS_trigger_formulas_partial_of_provider_formula_separation_strict
#print axioms fixed_formula_collapse_of_provider
#print axioms asymptotic_formula_collapse_of_slice_bridge
#print axioms ppolyFormula_fixed_of_asymptotic_slice
#print axioms asymptotic_formula_collapse_of_slice_agreement
#print axioms NP_not_subset_PpolyFormula_of_fixed_formula_collapse
#print axioms NP_not_subset_PpolyFormula_of_asymptotic_formula_collapse
#print axioms P_ne_NP_final_with_provider
#print axioms P_ne_NP_final

-- Regression checks for I-1 / I-3 readiness.
#print axioms Tests.i1_trivial_realization_available
#print axioms Tests.i1_trivial_ppolyreal_route_no_manual_embed
#print axioms Tests.i3_certificate_auto_no_manual_hCardHalf
#print axioms Tests.i4_final_wiring_of_formulaCertificate
#print axioms Tests.i4_final_wiring_of_supportBounds
#print axioms Tests.i4_final_wiring_of_multiswitching

-- Активный inclusion endpoint: no-arg, без внешнего `EvalAgreement`-контракта.
#print axioms Complexity.Simulation.proved_P_subset_PpolyDAG_internal
#print axioms Complexity.Simulation.proved_P_subset_PpolyDAG_internal_defeq_linear

-- Проверяем, что ключевые shrinkage-леммы не тянут лишних аксиом.
-- Это именно те утверждения, которые в TODO помечены для перепроверки.
#print axioms ThirdPartyFacts.partial_shrinkage_for_AC0
#print axioms ThirdPartyFacts.shrinkage_for_localCircuit
#print axioms ThirdPartyFacts.canonicalCCDT_CNF_aux_leafPartition_free
#print axioms ThirdPartyFacts.shrinkage_negDnfFamily_to_dnf_canonicalCCDT

-- Проверяем новый constructive I-4 трек через явный multi-switching witness.
#print axioms LowerBounds.noSmallAC0Solver_partial_of_multiSwitching
#print axioms LowerBounds.noSmallAC0Solver_partial_of_multiSwitching_provider
#print axioms AC0LocalityBridge.semantic_provider_semantic_link
#print axioms AC0LocalityBridge.package_semantic_link
#print axioms AC0LocalityBridge.formulaSemanticMultiSwitchingProvider_internal
#print axioms Magnification.formulaSemanticLinkPartial_of_provider
#print axioms Magnification.small_local_core_shrinks_under_restrictions_of_multiswitching_contract
#print axioms Magnification.alive_card_quarter_bound_of_multiswitching_contract
#print axioms Magnification.formula_support_core_steps_of_multiswitching_contract_and_size_step
#print axioms Magnification.formula_support_bounds_internal_of_core_steps
#print axioms Magnification.multiswitching_contract_of_semantic_provider_and_support_bounds
#print axioms Magnification.multiswitching_contract_of_semantic_provider_and_core_steps
#print axioms Magnification.multiswitching_contract_internalized_of_support_bounds
#print axioms Magnification.formula_support_bounds_and_semantic_link_from_multiswitching
#print axioms Magnification.formula_support_bounds_and_semantic_link_of_semantic_provider_and_support_bounds
#print axioms Magnification.formula_support_bounds_and_semantic_link_of_support_bounds
#print axioms LowerBounds.LB_Formulas_core_partial_of_multiSwitching
#print axioms LowerBounds.LB_Formulas_core_partial_of_multiSwitching_provider
#print axioms LowerBounds.LB_Formulas_core_partial_closed
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_noExists
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_of_syntacticLift
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_noExists_of_syntacticLift
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_iff_noExists
#print axioms LowerBounds.LB_Formulas_core_partial_closed_of_provider
#print axioms LowerBounds.LB_Formulas_core_partial_closed_internalized
#print axioms LowerBounds.LB_Formulas_core_partial_closed_of_syntacticLift_provider
#print axioms LowerBounds.LB_Formulas_core_partial_constructive_closed_of_provider
#print axioms Magnification.ac0_statement_from_pipeline_partial_closed
#print axioms Magnification.ac0_statement_from_pipeline_partial_providerClosed
#print axioms Magnification.ac0_statement_from_pipeline_partial_internalized
#print axioms Magnification.ac0_statement_from_pipeline_partial_providerClosed_of_syntacticLift
#print axioms Magnification.ac0_statement_from_pipeline_partial_constructive_providerClosed
#print axioms Magnification.ac0_statement_from_pipeline_partial_fully_closed
#print axioms Magnification.ac0_statement_exists_false_from_pipeline_partial_fully_closed
#print axioms Magnification.ac0_statement_from_pipeline_partial_fully_closed_of_syntacticLift
#print axioms Magnification.ac0_statement_exists_false_from_pipeline_partial_fully_closed_of_syntacticLift
#print axioms Magnification.ac0_statement_fully_closed_iff_noExists
#print axioms LowerBounds.noSmallLocalCircuitSolver_partial_constructive
#print axioms LowerBounds.antiChecker_testset_incompatibility_local_partial_constructive
