import Magnification.FinalResult
import Magnification.AC0AtlasBridge
import Magnification.AC0ApproxFamilyBridge
import LowerBounds.ApproxClassContradiction
import LowerBounds.ApproxClassNoGo
import LowerBounds.SingletonProvenanceEndpoint
import LowerBounds.SingletonDensityEndpoint
import LowerBounds.SingletonDensityContradiction
import Tests.BridgeLocalityRegression
import ThirdPartyFacts.Facts_Switching

/-!
  pnp3/Tests/AxiomsAudit.lean

  Тест-аудит: выводим список аксиом, от которых зависят ключевые теоремы.
  Этот файл компилируется вместе с проектом, чтобы случайные зависимости
  (например, от неожиданных внешних аксиом) были заметны сразу.
-/

open Pnp3
open Pnp3.ComplexityInterfaces
open Pnp3.Magnification

-- Итоговые утверждения (формульная сепарация).
#print axioms NP_not_subset_PpolyFormula_final
#print axioms NP_not_subset_PpolyFormula_final_with_provider
#print axioms NP_not_subset_PpolyFormula_final_with_supportBounds
#print axioms NP_not_subset_PpolyFormula_final_with_multiswitching
#print axioms asymptotic_formula_collapse
#print axioms NP_not_subset_PpolyReal_final
#print axioms NP_not_subset_PpolyReal_final_with_provider
#print axioms NP_not_subset_PpolyReal_final_with_supportBounds
#print axioms NP_not_subset_PpolyReal_final_with_multiswitching
#print axioms NP_not_subset_PpolyFormula_from_partial_formulas
#print axioms empty_witness_admissible_for_asymptotic_slice_of_nat_cmp

-- Мост от нижних оценок к `NP ⊄ PpolyFormula`.
#print axioms NP_not_subset_PpolyReal_from_partial_formulas
#print axioms OPS_trigger_formulas_partial_of_provider
#print axioms OPS_trigger_formulas_partial_of_provider_formula_separation_strict
#print axioms fixed_formula_collapse_of_provider
#print axioms asymptotic_formula_collapse_of_slice_bridge
#print axioms ppolyFormula_fixed_of_asymptotic_slice
#print axioms asymptotic_formula_collapse_of_slice_agreement
#print axioms NP_not_subset_PpolyFormula_of_fixed_formula_collapse
#print axioms NP_not_subset_PpolyFormula_of_asymptotic_formula_collapse
#print axioms P_ne_NP_final_with_provider
#print axioms P_ne_NP_final

-- Regression checks for I-1 / I-3 readiness.
#print axioms Tests.i1_trivial_realization_available
#print axioms Tests.i1_trivial_ppolyreal_route_no_manual_embed
#print axioms Tests.i3_certificate_auto_no_manual_hCardHalf
#print axioms Tests.i4_final_wiring_of_formulaCertificate
#print axioms Tests.i4_final_wiring_of_supportBounds
#print axioms Tests.i4_final_wiring_of_multiswitching

-- Активный inclusion endpoint: no-arg, без внешнего `EvalAgreement`-контракта.
#print axioms Complexity.Simulation.proved_P_subset_PpolyDAG_internal
#print axioms Complexity.Simulation.proved_P_subset_PpolyDAG_internal_defeq_linear

-- Проверяем, что ключевые shrinkage-леммы не тянут лишних аксиом.
-- Это именно те утверждения, которые в TODO помечены для перепроверки.
#print axioms ThirdPartyFacts.partial_shrinkage_for_AC0
#print axioms ThirdPartyFacts.shrinkage_for_localCircuit
#print axioms ThirdPartyFacts.canonicalCCDT_CNF_aux_leafPartition_free
#print axioms ThirdPartyFacts.shrinkage_negDnfFamily_to_dnf_canonicalCCDT

-- Проверяем новый constructive I-4 трек через явный multi-switching witness.
#print axioms LowerBounds.noSmallAC0Solver_partial_of_multiSwitching
#print axioms LowerBounds.noSmallAC0Solver_partial_of_multiSwitching_provider
#print axioms AC0LocalityBridge.semantic_provider_semantic_link
#print axioms AC0LocalityBridge.package_semantic_link
#print axioms AC0LocalityBridge.formulaSemanticMultiSwitchingProvider_internal
#print axioms AC0LocalityBridge.formulaSemanticMultiSwitchingProvider_internal_singleton_family
#print axioms AC0LocalityBridge.semanticSwitchingCertificate_internal
#print axioms AC0LocalityBridge.formulaSemanticMultiSwitchingProvider_internal_cert_length_eq_one
#print axioms AC0LocalityBridge.formulaSemanticMultiSwitchingProvider_internal_not_nontrivial_family
#print axioms AC0LocalityBridge.semanticSwitchingCertificate_of_provider
#print axioms AC0LocalityBridge.semanticSwitchingCertificateProvider_of_provider
#print axioms AC0LocalityBridge.semanticSwitchingNontrivialFamilyPackage_of_certificate
#print axioms AC0LocalityBridge.semanticSwitchingNontrivialFamilyProvider_of_certificateProvider_and_length
#print axioms AC0AtlasBridge.boundedAtlasScenario_of_semanticSwitchingCertificate
#print axioms AC0AtlasBridge.scenarioBudget_of_semanticSwitchingCertificate
#print axioms AC0AtlasBridge.semanticSwitchingScenarioBudget_no_large_gap
#print axioms AC0AtlasBridge.linked_testset_of_semanticSwitchingScenarioBudget
#print axioms AC0AtlasBridge.semanticSwitchingSmallMismatchPackage_of_extraction
#print axioms AC0AtlasBridge.linked_small_testset_of_boundedAtlasScenario
#print axioms AC0AtlasBridge.linked_small_testset_of_semanticSwitchingSmallMismatchPackage
#print axioms AC0AtlasBridge.semanticSwitchingSmallMismatchProvider_of_boundedAtlasScenarioProvider_and_extraction
#print axioms AC0AtlasBridge.linked_small_testset_provider_of_semanticSwitchingSmallMismatchProvider
#print axioms contradiction_of_semanticSwitchingApproxFamilyPackage
#print axioms no_ppolyFormula_of_semanticSwitchingApproxFamilyProvider
#print axioms NP_strict_not_subset_PpolyFormula_of_semanticSwitchingApproxFamilyProvider
#print axioms NP_not_subset_PpolyFormula_of_semanticSwitchingApproxFamilyProvider
#print axioms Counting.exists_small_testset_for_fixed_approximant_iff
#print axioms Counting.exists_small_testset_iff_exists_small_mismatch_approximant
#print axioms Counting.distU_perm
#print axioms Counting.unionClass_perm_fixed
#print axioms Counting.unionClass_perm_fixed_of_perm
#print axioms Counting.unionClass_perm
#print axioms Counting.approxClass_perm_fixed
#print axioms Counting.approxClass_perm_fixed_of_perm
#print axioms Counting.approxClass_perm
#print axioms Counting.one_le_unionBound
#print axioms LowerBounds.linked_function_in_approxClass_of_semanticSwitchingScenarioBudget
#print axioms LowerBounds.current_source_route_gives_singleton_approxClass
#print axioms LowerBounds.current_source_route_no_two_point_family
#print axioms LowerBounds.singletonProvenancePackage_of_internal_provider
#print axioms LowerBounds.singletonProvenance_boundedWitness
#print axioms LowerBounds.linked_function_in_approxClass_of_singletonProvenancePackage
#print axioms LowerBounds.smallMismatchPackage_of_singletonProvenancePackage_of_mismatch_card_le
#print axioms LowerBounds.singletonDensityPackage_of_internal_provider
#print axioms LowerBounds.approxOnNaturalMismatchTestset_of_singletonDensityPackage
#print axioms LowerBounds.naturalMismatchTestset_density_le_of_singletonDensityPackage
#print axioms LowerBounds.naturalMismatchTestset_density_le_inv_of_singletonDensityPackage
#print axioms LowerBounds.naturalMismatchTestset_card_le_inv_mul_pow_of_singletonDensityPackage
#print axioms LowerBounds.linked_natural_testset_density_of_internal_provider
#print axioms LowerBounds.old_testset_endpoint_of_singletonDensityPackage_of_testsetCapacity_lt_one
#print axioms LowerBounds.one_le_testsetCapacity
#print axioms LowerBounds.not_testsetCapacity_lt_one
#print axioms LowerBounds.naturalMismatchTestset_not_testsetCapacity_lt_one_of_singletonDensityPackage
#print axioms LowerBounds.abstractSingletonDensityPayload_of_singletonDensityPackage
#print axioms LowerBounds.nonempty_abstractSingletonDensityPayload_false
#print axioms LowerBounds.abstractLinkedSingletonDensityPayload_of_abstract
#print axioms LowerBounds.nonempty_abstractLinkedSingletonDensityPayload_false
#print axioms LowerBounds.abstractLinkedSingletonDensityPayload_of_singletonDensityPackage
#print axioms LowerBounds.abstractTargetedSingletonDensityPayload_of_singletonDensityPackage
#print axioms LowerBounds.nonempty_abstractTargetedSingletonDensityPayload_false
#print axioms LowerBounds.abstractGapTargetedSingletonDensityPayload_of_singletonDensityPackage
#print axioms LowerBounds.approxOnNaturalMismatchTestset_of_abstractSingletonDensityPayload
#print axioms LowerBounds.naturalMismatchTestset_density_le_inv_of_abstractSingletonDensityPayload
#print axioms LowerBounds.old_testset_endpoint_of_abstractSingletonDensityPayload_of_testsetCapacity_lt_one
#print axioms LowerBounds.naturalMismatchTestset_not_testsetCapacity_lt_one_of_abstractSingletonDensityPayload
#print axioms LowerBounds.abstractSingletonDensityPayload_of_internal_provider
#print axioms LowerBounds.abstractLinkedSingletonDensityPayload_of_internal_provider
#print axioms LowerBounds.abstractTargetedSingletonDensityPayload_of_internal_provider
#print axioms LowerBounds.abstractGapTargetedSingletonDensityPayload_of_internal_provider
#print axioms LowerBounds.abstractGapTargetedSingletonDensityPayload_of_dag
#print axioms LowerBounds.not_ppolyDAG_of_abstractGapTargeted_consumer
#print axioms LowerBounds.NP_not_subset_PpolyDAG_of_abstractGapTargeted_consumer
#print axioms LowerBounds.NP_not_subset_PpolyDAG_of_abstractGapTargeted_consumer_TM
#print axioms LowerBounds.mismatchSet_false_indicator_eq
#print axioms LowerBounds.approxClass_does_not_imply_small_mismatch
#print axioms AC0AtlasBridge.boundedAtlasScenarioProvider_of_semanticSwitchingCertificateProvider
#print axioms AC0AtlasBridge.scenarioBudgetProvider_of_semanticSwitchingCertificateProvider
#print axioms AC0AtlasBridge.boundedAtlasScenarioProvider_of_formulaSemanticMultiSwitchingProvider_internal
#print axioms AC0AtlasBridge.scenarioBudgetProvider_of_formulaSemanticMultiSwitchingProvider_internal
#print axioms Magnification.formulaSemanticLinkPartial_of_provider
#print axioms Magnification.formula_witness_yields_polylog_support_of_multiswitching_contract
#print axioms Magnification.small_local_core_shrinks_under_restrictions_of_multiswitching_contract
#print axioms Magnification.alive_card_quarter_bound_of_multiswitching_contract
#print axioms Magnification.formula_support_core_steps_of_multiswitching_contract
#print axioms Magnification.formula_support_bounds_internal_of_core_steps
#print axioms Magnification.formula_support_bounds_of_extracted_local_core_provider
#print axioms Magnification.formulaRestrictionCertificateData_of_generic_extracted_local_core_provider
#print axioms Magnification.multiswitching_contract_of_semantic_provider_and_support_bounds
#print axioms Magnification.multiswitching_contract_of_semantic_provider_and_core_steps
#print axioms Magnification.multiswitching_contract_internalized_of_support_bounds
#print axioms Magnification.formula_support_bounds_and_semantic_link_from_multiswitching
#print axioms Magnification.formula_support_bounds_and_semantic_link_of_semantic_provider_and_support_bounds
#print axioms Magnification.formula_support_bounds_and_semantic_link_of_support_bounds
#print axioms Magnification.extracted_local_core_provider_of_multiswitching_contract
#print axioms Magnification.generic_extracted_local_core_provider_of_multiswitching_contract
#print axioms Magnification.solverDecideFacts_stable_of_current_extracted_restriction
#print axioms Magnification.promisePreservingWeakGenericExtractedLocalCoreProvider_of_supportBounds
#print axioms Magnification.promisePreservingWeakGenericExtractedLocalCoreProvider_of_multiswitching_contract
#print axioms Magnification.weakGenericExtractedLocalCoreProvider_of_generic
#print axioms Magnification.weakGenericExtractedLocalCore_of_semantic_switching_certificate_and_extraction
#print axioms Magnification.weakGenericExtractedLocalCoreProvider_of_semantic_switching_certificate_provider_and_extraction
#print axioms Magnification.weakGenericExtractedLocalCoreProvider_of_semantic_provider_and_extraction
#print axioms Magnification.promisePreservingWeakGenericExtractedLocalCoreProvider_of_generic
#print axioms Magnification.promisePreservingWeakGenericExtractedLocalCoreProvider_of_weak_provider_and_preservation
#print axioms Magnification.genericRestrictedLocalBehaviorTransport_of_core
#print axioms Magnification.genericRestrictedLocalBehaviorTransport_of_weak_core
#print axioms Magnification.globalization_of_decision_preservation_on_promise
#print axioms Magnification.globalization_probe_of_decision_preservation
#print axioms Magnification.globalization_of_decision_preservation_on_promise_weak
#print axioms Magnification.globalization_probe_of_weak_decision_preservation
#print axioms Magnification.solvesPromise_of_promisePreservingWeakGenericExtractedLocalCore
#print axioms Magnification.restrictedBehaviorDecisionPreservationOnPromise_of_generic_extracted_local_core
#print axioms Magnification.globalization_of_generic_extracted_local_core
#print axioms Magnification.genericRestrictedBehaviorProvider_of_generic_extracted_local_core_provider_and_transport
#print axioms Magnification.weakGenericRestrictedBehaviorProvider_of_weak_generic_extracted_local_core_provider_and_transport
#print axioms Magnification.genericRestrictedLocalCertificateProvider_of_generic_extracted_local_core_provider_and_transport
#print axioms Magnification.structuredLocalityProviderPartial_of_generic_extracted_local_core_provider
#print axioms Magnification.structuredLocalityProviderPartial_of_generic_restricted_behavior_provider_and_globalize
#print axioms Magnification.structuredLocalityProviderPartial_of_weak_generic_restricted_behavior_provider_and_globalize
#print axioms Magnification.structuredLocalityProviderPartial_of_promisePreservingWeakGenericCoreProvider_and_behavior_transport
#print axioms Magnification.structuredLocalityProviderPartial_of_promisePreservingWeakGenericCoreProvider
#print axioms Magnification.structuredLocalityProviderPartial_of_supportBounds_via_promisePreservingWeakCore
#print axioms Magnification.structuredLocalityProviderPartial_of_generic_restricted_local_certificate_provider
#print axioms Magnification.structuredLocalityProviderPartial_of_generic_extracted_local_core_provider_and_transport
#print axioms Magnification.structuredLocalityProviderPartial_of_generic_extracted_local_core_provider_and_behavior_transport
#print axioms Magnification.structuredLocalityProviderPartial_of_generic_extracted_local_core_provider_and_behavior_transport_and_globalize
#print axioms Magnification.structuredLocalityProviderPartial_of_weak_generic_extracted_local_core_provider_and_behavior_transport_and_globalize
#print axioms Magnification.structuredLocalityProviderPartial_of_generic_extracted_local_core_provider_via_promisePreservingWeakCore
#print axioms Magnification.structuredLocalityProviderPartial_of_extracted_local_core_provider
#print axioms Magnification.structuredLocalityProviderPartial_of_multiswitching_contract_via_extracted_local_core
#print axioms Magnification.structuredLocalityProviderPartial_of_multiswitching_contract_via_generic_extracted_local_core
#print axioms Magnification.structuredLocalityProviderPartial_of_multiswitching_contract_via_promisePreservingWeakCore
#print axioms LowerBounds.LB_Formulas_core_partial_of_multiSwitching
#print axioms LowerBounds.LB_Formulas_core_partial_of_multiSwitching_provider
#print axioms LowerBounds.LB_Formulas_core_partial_closed
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_noExists
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_of_syntacticLift
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_noExists_of_syntacticLift
#print axioms LowerBounds.LB_Formulas_core_partial_fully_closed_iff_noExists
#print axioms LowerBounds.LB_Formulas_core_partial_closed_of_provider
#print axioms LowerBounds.LB_Formulas_core_partial_closed_internalized
#print axioms LowerBounds.LB_Formulas_core_partial_closed_of_syntacticLift_provider
#print axioms LowerBounds.LB_Formulas_core_partial_constructive_closed_of_provider
#print axioms Magnification.ac0_statement_from_pipeline_partial_closed
#print axioms Magnification.ac0_statement_from_pipeline_partial_providerClosed
#print axioms Magnification.ac0_statement_from_pipeline_partial_internalized
#print axioms Magnification.ac0_statement_from_pipeline_partial_providerClosed_of_syntacticLift
#print axioms Magnification.ac0_statement_from_pipeline_partial_constructive_providerClosed
#print axioms Magnification.ac0_statement_from_pipeline_partial_fully_closed
#print axioms Magnification.ac0_statement_exists_false_from_pipeline_partial_fully_closed
#print axioms Magnification.ac0_statement_from_pipeline_partial_fully_closed_of_syntacticLift
#print axioms Magnification.ac0_statement_exists_false_from_pipeline_partial_fully_closed_of_syntacticLift
#print axioms Magnification.ac0_statement_fully_closed_iff_noExists
#print axioms LowerBounds.noSmallLocalCircuitSolver_partial_constructive
#print axioms LowerBounds.antiChecker_testset_incompatibility_local_partial_constructive
