import Tests.TMGateNFirstRequestLaunchSurfaceTests
import Tests.TMGateNValuesWriterSurfaceTests

/-! Direct owner and surface audit roots, including the revised writer row. -/
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_requestReady_allBlank_reject_exact
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_requestReady_allBlank_reject_exact
#print axioms Pnp3.Internal.PsubsetPpoly.TM.GNFirstRequestLaunchProbes.literal_noBof_allBlank_launch_reject
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_literal_noBof_allBlank_launch_reject
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnTransition_launch_rows
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnTransition_launch_rows
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnTransition_launch_decision
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnTransition_launch_decision
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_launch_onList_exact
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_launch_onList_exact
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_requestReady_reserved1101_reject_five
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_requestReady_reserved1101_reject_five
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_requestReady_reserved1101_reject_stable
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_requestReady_reserved1101_reject_stable
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnFirstRequestReady_geometry
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnFirstRequestReady_geometry
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnFirstLaunchSteps_provenance
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnFirstLaunchSteps_provenance
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_requestReady_launch_exact
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_requestReady_launch_exact
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_encodeGN_firstLaunch_exact
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_encodeGN_firstLaunch_exact
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_encodeGN_firstOutputDone_exact
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_encodeGN_firstOutputDone_exact
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnCS_encodeGN_firstReturned_exact
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnCS_encodeGN_firstReturned_exact
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnFirstReturned_structure
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_gnFirstReturned_structure
#print axioms Pnp3.Internal.PsubsetPpoly.TM.GNFirstRequestLaunchProbes.literal_cap_firstLaunch
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_literal_cap_firstLaunch
#print axioms Pnp3.Internal.PsubsetPpoly.TM.GNFirstRequestLaunchProbes.literal_cap_firstReturned
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_literal_cap_firstReturned
#print axioms Pnp3.Internal.PsubsetPpoly.TM.GNFirstRequestLaunchProbes.literal_cap_launch_executable
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_literal_cap_launch_executable
#print axioms Pnp3.Internal.PsubsetPpoly.TM.GNFirstRequestLaunchProbes.literal_first_not_is_undefined
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_literal_first_not_is_undefined
#print axioms Pnp3.Internal.PsubsetPpoly.TM.GNFirstRequestLaunchProbes.literal_reserved_launch_reject
#print axioms Pnp3.Tests.TMGateNFirstRequestLaunchSurface.check_literal_reserved_launch_reject
#print axioms Pnp3.Internal.PsubsetPpoly.TM.gnTransition_values_rows
#print axioms Pnp3.Tests.TMGateNValuesWriterSurface.check_gnTransition_values_rows
